### ISSUE TITLE
Fail to link with snappy.o

### ISSUE THREAD

**Issue by jiaozi226** [edenhill/librdkafka#470] opened 2015-12-23 07:36 UTC
When compiling the examples, the following link error occurs. I looked into the code and found htole16  as a macro rather than a defined function. The same problem pops out when I compile my own code depending on the generated librdkafka++.a and librdkafa.a. Thank you.
    

        librdkafka/src/snappy.c:652: undefined reference to `htole16'
        librdkafka/src/snappy.c:652: undefined reference to `htole16'
        librdkafka/src/snappy.c:652: undefined reference to `htole16'
        ../src/librdkafka.a(snappy.o): In function `decompress_all_tags':
        librdkafka/src/snappy.c:1233: undefined reference to `le32toh'
        librdkafka/src/snappy.c:1208: undefined reference to `le32toh'

**Comment by jiaozi226** [comment] 2015-12-23 07:59
The following warnings are also found when building the libs. It seems the macros did not work, and the compiler process the symbol as functions.

      snappy.c:652:3: warning: implicit declaration of function ‘htole16’ [-Wimplicit-function-declaration]
      put_unaligned_le16(offset, op);
      ^
     snappy.c: In function ‘decompress_all_tags’:
     snappy.c:1208:5: warning: implicit declaration of function ‘le32toh’ [-Wimplicit-function-declaration]
        literal_length = (get_unaligned_le32(ip) &

**Comment by jiaozi226** [comment] 2015-12-23 10:24
Appending More information:
 Operating System :CentOs

I looked into the code in "src/snappy_compact.h" ，and saw some macro definitions for htole16.
 Should I specify options when configuring to enable one of the macro definition?

**Comment by jiaozi226** [comment] 2015-12-23 10:55
I tested the macro definitions by adding nonsense code into different #ifdef #endif blocks. And identified the following line did not work on my machine at src/snappy_compact.h ,line 139:

   #if __LITTLE_ENDIAN__ == 1 && (defined(__LSB_VERSION__) || defined(__WIN32__))

The problem is not  (defined(__LSB_VERSION__) || defined(__WIN32__)) is false on my machine, While little endian is true. By Modifying the line as the following , the build process was successful.

    #if __LITTLE_ENDIAN__ == 1

Is it the correct way to solve the problem?

**Comment by edenhill** [comment] 2015-12-27 20:56
Thanks for taking the time to find the root cause of the issue, it really helps.

What CentOS version are you using?

**Comment by edenhill** [comment] 2016-01-10 22:36
ping @jiaozi226 , what CentOS version? Looking to reproduce this on a VM image

**Comment by edenhill** [comment] 2016-01-11 09:29
Fixed on master

**Closed by edenhill** 2016-01-11 09:29 UTC
Labels: bug
