### ISSUE TITLE
Stack corruption in rd_kafka_anyconf_copy()

### ISSUE THREAD

**Issue by mooware** [edenhill/librdkafka#1416] opened 2017-09-07 14:54 UTC
Description
===========

When building for MSVC with runtime checks enabled (-RTC1), the function rd_kafka_anyconf_copy() causes a minor stack corruption.

When looking at the issue in a debugger, I saw that it occurs in https://github.com/edenhill/librdkafka/blob/v0.11.0/src/rdkafka_conf.c#L1511 and following. The variable "valsz" was zero for some reason, leading to an rd_alloca() allocation for zero bytes. The next line calls rd_kafka_anyconf_get0() with the zero-byte allocation, which calls rd_kafka_conf_flags2str(), where a null-byte is written to the zero-byte allocation (https://github.com/edenhill/librdkafka/blob/v0.11.0/src/rdkafka_conf.c#L1749).

I would guess that this bug might not have any real-world consequences when the application does not explicitly check for stack corruptions, because the overwritten byte can very easily be just some unused garbage.

How to reproduce
================

Build librdkafka with Microsoft Visual C++ (2015 in my case), configure a debug build with runtime checks (option -RTC1).

Run any code example that creates an RdKafka::Conf object.

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): v0.11.0
 - [x] Apache Kafka version: 2.12
 - [x] librdkafka client configuration: see above
 - [x] Operating system: Windows 7
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment] 2017-09-07 14:56
Thank you for analysis.
This looks like a duplicate of #1334.

**Closed** 2017-09-07 14:57 UTC
Labels: bug, duplicate
