### ISSUE TITLE
outq_len() increments on unknown topic and never resets to 0

### ISSUE THREAD

**Issue by ajay2170** [edenhill/librdkafka#2424] opened 2019-07-22 22:21 UTC
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
producer outq_len is incremented and never reset to zero when message is sent to an unknown topic.

How to reproduce
================
Step 1: produce a message to an unknown topic (topic not existing).
Step 2: Check outq_len, it would be incremented to 1.
Step 3: Run the below code to check outq_len continuously:
while ( _producer->outq_len() > 0 )
{
     _producer->poll(5000);
     cout<< _producer->outq_len();
}

Observed: outq_len() remain 1 indefinitely.

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<1.0.0>`
 - [x] Apache Kafka version: `<2.11.0>`
 - [x] librdkafka client configuration: `<queue_buffering_max_ms = 0>`
 - [x] Operating system: `<Redhat 7.4>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by ajay2170** [comment] 2019-07-31 20:44
Hi.. could you please respond ? I am wondering now if this is how an issue is raised, since I haven't seen any response yet. Thanks.

**Comment by edenhill** [comment] 2019-08-01 10:00
I can't reproduce this.

Please reproduce with `debug=protocol,msg,queue` and provide the logs

**Comment by ajay2170** [comment] 2019-08-01 16:17
Thanks for your response. Please see below the log, as requested.
It seems to be happening when the same producer is used to send a message to two topic, 1 known and 1 unknown.

Step 1: sent message to known topic AJAY-ATLBHS1. outq length becomes 1. Polled, Received ack. outq length becomes 0
Step 2: sent message to unknown topic ATL-ATLBHS2X. outq length becomes 1. Polled, Received error "Broker: Unknown topic or partition". It seems at this point, the outq length is not decremented to 0.
Step 3: sent message to known topic AJAY-ATLBHS1. Outq length incremented to 2. Polled, Received ack. outq length is decremented to 1. No matter how many poll you do after this, length remains at 1.

%7|1564675432.843|WAKEUPFD|PRODUCER-router-0-AJAY-KAFKA#producer-1| [thrd:app]: 10.0.0.35:9092/bootstrap: Enabled low-latency ops queue wake-ups
%7|1564675432.843|INIT|PRODUCER-router-0-AJAY-KAFKA#producer-1| [thrd:app]: librdkafka v1.0.0 (0x10000ff) PRODUCER-router-0-AJAY-KAFKA#producer-1 initialized (builtin.features gzip,snappy,ssl,sasl,regex,lz4,sasl_gssapi,sasl_plain,sasl_scram,plugins, GCC GXX PKGCONFIG INSTALL GNULD LDS LIBDL PLUGINS ZLIB SSL SASL_CYRUS HDRHISTOGRAM SNAPPY SOCKEM SASL_SCRAM CRC32C_HW, debug 0xe0)
%7|1564675432.844|CONNECTED|PRODUCER-router-0-AJAY-KAFKA#producer-1| [thrd:10.0.0.35:9092/bootstrap]: 10.0.0.35:9092/bootstrap: Connected (#1)
%7|1564675432.844|FEATURE|PRODUCER-router-0-AJAY-KAFKA#producer-1| [thrd:10.0.0.35:9092/bootstrap]: 10.0.0.35:9092/bootstrap: Updated enabled protocol features +ApiVersion to ApiVersion
%7|1564675432.844|SEND|PRODUCER-router-0-AJAY-KAFKA#producer-1| [thrd:10.0.0.35:9092/bootstrap]: 10.0.0.35:9092/bootstrap: Sent ApiVersionRequest (v0, 46 bytes @ 0, CorrId 1)
%7|1564675432.844|RECV|PRODUCER-router-0-AJAY-KAFKA#producer-1| [thrd:10.0.0.35:9092/bootstrap]: 10.0.0.35:9092/bootstrap: Received ApiVersionResponse (v0, 264 bytes, CorrId 1, rtt 0.42ms)
%7|1564675432.844|SEND|PRODUCER-router-0-AJAY-KAFKA#producer-1| [thrd:10.0.0.35:9092/bootstrap]: 10.0.0.35:9092/bootstrap: Sent MetadataRequest (v2, 46 bytes @ 0, CorrId 2)
%7|1564675432.844|SEND|PRODUCER-router-0-AJAY-KAFKA#producer-1| [thrd:10.0.0.35:9092/bootstrap]: 10.0.0.35:9092/bootstrap: Sent MetadataRequest (v2, 46 bytes @ 0, CorrId 3)
%7|1564675432.845|RECV|PRODUCER-router-0-AJAY-KAFKA#producer-1| [thrd:10.0.0.35:9092/bootstrap]: 10.0.0.35:9092/bootstrap: Received MetadataResponse (v2, 57 bytes, CorrId 2, rtt 0.31ms)
%7|1564675432.848|RECV|PRODUCER-router-0-AJAY-KAFKA#producer-1| [thrd:10.0.0.35:9092/bootstrap]: 10.0.0.35:9092/0: Received MetadataResponse (v2, 37115 bytes, CorrId 3, rtt 3.93ms)
%7|1564675435.912|TOPPAR|PRODUCER-router-0-AJAY-KAFKA#producer-1| [thrd:10.0.0.35:9092/bootstrap]: 10.0.0.35:9092/0: AJAY-ATLBHS1 [0] 1 message(s) in xmit queue (1 added from partition queue)
%7|1564675435.912|PRODUCE|PRODUCER-router-0-AJAY-KAFKA#producer-1| [thrd:10.0.0.35:9092/bootstrap]: 10.0.0.35:9092/0: AJAY-ATLBHS1 [0]: Produce MessageSet with 1 message(s) (809 bytes, ApiVersion 6, MsgVersion 2, MsgId 0, BaseSeq -1, PID{Invalid})
%7|1564675435.912|SEND|PRODUCER-router-0-AJAY-KAFKA#producer-1| [thrd:10.0.0.35:9092/bootstrap]: 10.0.0.35:9092/0: Sent ProduceRequest (v6, 889 bytes @ 0, CorrId 4)
%7|1564675435.912|RECV|PRODUCER-router-0-AJAY-KAFKA#producer-1| [thrd:10.0.0.35:9092/bootstrap]: 10.0.0.35:9092/0: Received ProduceResponse (v6, 56 bytes, CorrId 4, rtt 0.49ms)
%7|1564675435.912|MSGSET|PRODUCER-router-0-AJAY-KAFKA#producer-1| [thrd:10.0.0.35:9092/bootstrap]: 10.0.0.35:9092/0: AJAY-ATLBHS1 [0]: MessageSet with 1 message(s) (MsgId 0, BaseSeq -1) delivered
%7|1564675436.845|SEND|PRODUCER-router-0-AJAY-KAFKA#producer-1| [thrd:10.0.0.35:9092/bootstrap]: 10.0.0.35:9092/0: Sent MetadataRequest (v2, 61 bytes @ 0, CorrId 5)
%7|1564675436.846|RECV|PRODUCER-router-0-AJAY-KAFKA#producer-1| [thrd:10.0.0.35:9092/bootstrap]: 10.0.0.35:9092/0: Received MetadataResponse (v2, 79 bytes, CorrId 5, rtt 0.46ms)
%7|1564675437.047|TOPPAR|PRODUCER-router-0-AJAY-KAFKA#producer-1| [thrd:10.0.0.35:9092/bootstrap]: 10.0.0.35:9092/0: AJAY-ATLBHS1 [0] 1 message(s) in xmit queue (1 added from partition queue)
%7|1564675437.047|PRODUCE|PRODUCER-router-0-AJAY-KAFKA#producer-1| [thrd:10.0.0.35:9092/bootstrap]: 10.0.0.35:9092/0: AJAY-ATLBHS1 [0]: Produce MessageSet with 1 message(s) (809 bytes, ApiVersion 6, MsgVersion 2, MsgId 0, BaseSeq -1, PID{Invalid})
%7|1564675437.047|SEND|PRODUCER-router-0-AJAY-KAFKA#producer-1| [thrd:10.0.0.35:9092/bootstrap]: 10.0.0.35:9092/0: Sent ProduceRequest (v6, 889 bytes @ 0, CorrId 6)
%7|1564675437.048|RECV|PRODUCER-router-0-AJAY-KAFKA#producer-1| [thrd:10.0.0.35:9092/bootstrap]: 10.0.0.35:9092/0: Received ProduceResponse (v6, 56 bytes, CorrId 6, rtt 0.54ms)
%7|1564675437.048|MSGSET|PRODUCER-router-0-AJAY-KAFKA#producer-1| [thrd:10.0.0.35:9092/bootstrap]: 10.0.0.35:9092/0: AJAY-ATLBHS1 [0]: MessageSet with 1 message(s) (MsgId 0, BaseSeq -1) delivered
%7|1564675437.846|SEND|PRODUCER-router-0-AJAY-KAFKA#producer-1| [thrd:10.0.0.35:9092/bootstrap]: 10.0.0.35:9092/0: Sent MetadataRequest (v2, 61 bytes @ 0, CorrId 7)
%7|1564675437.846|RECV|PRODUCER-router-0-AJAY-KAFKA#producer-1| [thrd:10.0.0.35:9092/bootstrap]: 10.0.0.35:9092/0: Received MetadataResponse (v2, 79 bytes, CorrId 7, rtt 0.44ms)
%7|1564675438.846|SEND|PRODUCER-router-0-AJAY-KAFKA#producer-1| [thrd:10.0.0.35:9092/bootstrap]: 10.0.0.35:9092/0: Sent MetadataRequest (v2, 61 bytes @ 0, CorrId 8)
%7|1564675438.846|RECV|PRODUCER-router-0-AJAY-KAFKA#producer-1| [thrd:10.0.0.35:9092/bootstrap]: 10.0.0.35:9092/0: Received MetadataResponse (v2, 79 bytes, CorrId 8, rtt 0.49ms)
%7|1564675439.846|SEND|PRODUCER-router-0-AJAY-KAFKA#producer-1| [thrd:10.0.0.35:9092/bootstrap]: 10.0.0.35:9092/0: Sent MetadataRequest (v2, 61 bytes @ 0, CorrId 9)
%7|1564675439.846|RECV|PRODUCER-router-0-AJAY-KAFKA#producer-1| [thrd:10.0.0.35:9092/bootstrap]: 10.0.0.35:9092/0: Received MetadataResponse (v2, 79 bytes, CorrId 9, rtt 0.48ms)
%7|1564675440.848|SEND|PRODUCER-router-0-AJAY-KAFKA#producer-1| [thrd:10.0.0.35:9092/bootstrap]: 10.0.0.35:9092/0: Sent MetadataRequest (v2, 61 bytes @ 0, CorrId 10)
%7|1564675440.848|RECV|PRODUCER-router-0-AJAY-KAFKA#producer-1| [thrd:10.0.0.35:9092/bootstrap]: 10.0.0.35:9092/0: Received MetadataResponse (v2, 79 bytes, CorrId 10, rtt 0.51ms)
%7|1564675441.848|SEND|PRODUCER-router-0-AJAY-KAFKA#producer-1| [thrd:10.0.0.35:9092/bootstrap]: 10.0.0.35:9092/0: Sent MetadataRequest (v2, 61 bytes @ 0, CorrId 11)
%7|1564675441.848|RECV|PRODUCER-router-0-AJAY-KAFKA#producer-1| [thrd:10.0.0.35:9092/bootstrap]: 10.0.0.35:9092/0: Received MetadataResponse (v2, 79 bytes, CorrId 11, rtt 0.49ms)
%7|1564675442.850|SEND|PRODUCER-router-0-AJAY-KAFKA#producer-1| [thrd:10.0.0.35:9092/bootstrap]: 10.0.0.35:9092/0: Sent MetadataRequest (v2, 61 bytes @ 0, CorrId 12)
%7|1564675442.850|RECV|PRODUCER-router-0-AJAY-KAFKA#producer-1| [thrd:10.0.0.35:9092/bootstrap]: 10.0.0.35:9092/0: Received MetadataResponse (v2, 79 bytes, CorrId 12, rtt 0.51ms)
%7|1564675443.850|SEND|PRODUCER-router-0-AJAY-KAFKA#producer-1| [thrd:10.0.0.35:9092/bootstrap]: 10.0.0.35:9092/0: Sent MetadataRequest (v2, 61 bytes @ 0, CorrId 13)
%7|1564675443.851|RECV|PRODUCER-router-0-AJAY-KAFKA#producer-1| [thrd:10.0.0.35:9092/bootstrap]: 10.0.0.35:9092/0: Received MetadataResponse (v2, 79 bytes, CorrId 13, rtt 0.55ms)
%7|1564675444.851|SEND|PRODUCER-router-0-AJAY-KAFKA#producer-1| [thrd:10.0.0.35:9092/bootstrap]: 10.0.0.35:9092/0: Sent MetadataRequest (v2, 61 bytes @ 0, CorrId 14)
%7|1564675444.852|RECV|PRODUCER-router-0-AJAY-KAFKA#producer-1| [thrd:10.0.0.35:9092/bootstrap]: 10.0.0.35:9092/0: Received MetadataResponse (v2, 79 bytes, CorrId 14, rtt 0.51ms)
%7|1564675445.853|SEND|PRODUCER-router-0-AJAY-KAFKA#producer-1| [thrd:10.0.0.35:9092/bootstrap]: 10.0.0.35:9092/0: Sent MetadataRequest (v2, 61 bytes @ 0, CorrId 15)
%7|1564675445.854|RECV|PRODUCER-router-0-AJAY-KAFKA#producer-1| [thrd:10.0.0.35:9092/bootstrap]: 10.0.0.35:9092/0: Received MetadataResponse (v2, 79 bytes, CorrId 15, rtt 0.51ms)
%7|1564675446.853|SEND|PRODUCER-router-0-AJAY-KAFKA#producer-1| [thrd:10.0.0.35:9092/bootstrap]: 10.0.0.35:9092/0: Sent MetadataRequest (v2, 61 bytes @ 0, CorrId 16)
%7|1564675446.854|RECV|PRODUCER-router-0-AJAY-KAFKA#producer-1| [thrd:10.0.0.35:9092/bootstrap]: 10.0.0.35:9092/0: Received MetadataResponse (v2, 79 bytes, CorrId 16, rtt 0.47ms)
%7|1564675447.853|SEND|PRODUCER-router-0-AJAY-KAFKA#producer-1| [thrd:10.0.0.35:9092/bootstrap]: 10.0.0.35:9092/0: Sent MetadataRequest (v2, 61 bytes @ 0, CorrId 17)
%7|1564675447.854|RECV|PRODUCER-router-0-AJAY-KAFKA#producer-1| [thrd:10.0.0.35:9092/bootstrap]: 10.0.0.35:9092/0: Received MetadataResponse (v2, 79 bytes, CorrId 17, rtt 0.50ms)

**Comment by ajay2170** [comment] 2019-08-07 14:20
Hi, please let me know if the log was useful, or if you need any more details. Thanks.

**Comment by edenhill** [comment] 2019-08-31 08:23
Interesting, there is no mention of AJAY-ATLBHS2X in the logs.
You might be hitting this issue https://github.com/edenhill/librdkafka/commit/4680d62c6a00e413bd361bf8a9f868c3bd4fd9ba
 which is fixed in the upcoming v1.2.0 release.

**Comment by ajay2170** [comment] 2019-09-06 16:21
Thanks. Any tentative schedule when 1.2.0 will be out ?

**Comment by edenhill** [comment] 2019-09-07 07:38
Next week, hopefully!

**Closed** 2020-03-12 14:25 UTC
