### ISSUE TITLE
Consumed wrong message with unexpected offset 

### ISSUE THREAD

**Issue by jimmy1911** [edenhill/librdkafka#411] opened 2015-11-07 07:05 UTC
I have produced 100,000 messages into topic rt_mem01 partiton 0.But when I consume this  partition, kafka return message with unexpected offset. Here are some logs of my program:

create topic offset:15         // consumer->start()   offset
Read msg at offset 15        // message->offset()
msg
     10.10.38.70rt_mem01*set2
key_15
create topic offset:16            // consume-> start offset
Read msg at offset 15371     // consumed message  with wrong offset 
msg
     10.10.38.70rt_mem01*set2

     key_15371
create topic offset:17
Read msg at offset 17            //next time it is right
msg
     10.10.38.70rt_mem01*set2
key_17
create topic offset:18
Read msg at offset 15373      //wrong again 
msg
     10.10.38.70rt_mem01*set2

     key_15373

In order to find the problem, I wrote a more simple program to debug and unlucky the result is the same. This progrom creates a topic when consume one message. I don't know is this no appropriate. And when I modified the example/rdkafka_example.cpp in this mode to consume, the result is the same as the log above. My program is shown below: 

int init_kafka(){
    brokers = "10.10.38.70:9501,10.10.38.70:9502,10.10.38.70:9503";
    /*
     *Create configuration objects
     */
    consumer_conf = RdKafka::Conf::create(RdKafka::Conf::CONF_GLOBAL); //global variable
    consumer_tconf = RdKafka::Conf::create(RdKafka::Conf::CONF_TOPIC); //global variable
    producer_conf = RdKafka::Conf::create(RdKafka::Conf::CONF_GLOBAL); //global variable
    producer_tconf = RdKafka::Conf::create(RdKafka::Conf::CONF_TOPIC); //global variable
    consumer_conf->set("metadata.broker.list", FLAGS_brokers, errstr);
    consumer_conf->set("queued.min.messages", "1000000", errstr);
    //consumer_conf->set("statistics.interval.ms", "60*1000", errstr);
    consumer_conf->set("event_cb", &ex_event_cb, errstr);

    producer_conf->set("metadata.broker.list", FLAGS_brokers, errstr);
    producer_conf->set("queue.buffering.max.messages", "1000000", errstr);
    //producer_conf->set("statistics.interval.ms", "60*1000", errstr);
    producer_conf->set("event_cb", &ex_event_cb, errstr);
    producer_conf->set("dr_cb", &ex_dr_cb, errstr);
    producer = RdKafka::Producer::create(producer_conf, errstr);//global variable
    if (!producer) {
        std::cerr << "Failed to create producer: " << errstr << std::endl;
        exit(1);
    }

   consumer = RdKafka::Consumer::create(consumer_conf, errstr);//global variable
    if (!consumer) {
        std::cerr << "Failed to create consumer: " << errstr << std::endl;
        exit(1);
    }
   /*only consume 1000 message*/
    for (int64_t k =0;k<1000;k++){
        /*create a topic when consume every message */
        RdKafka::Topic *topic = RdKafka::Topic::create(consumer, string("rt_mem01"),consumer_tconf, errstr);
        if (!topic) {
            std::cerr << "Failed to create topic: " << errstr << std::endl;
            exit(1);
        }
        cout<<"create topic offset:"<<(int64_t)(k)<<endl;
        RdKafka::ErrorCode resp = consumer->start(topic, 0, (int64_t)(k));
        if (resp != RdKafka::ERR_NO_ERROR) {
            std::cerr << "Failed to start consumer: " <<RdKafka::err2str(resp) << std::endl;
            exit(1);
        }        
        RdKafka::Message *msg = consumer->consume(topic, 0, 1000);
        std::cout << "Read msg at offset " << msg->offset() << std::endl;
        delete msg;
        consumer->poll(0);
        }
        consumer->stop(topic, 0);
        consumer->poll(1000);
        delete topic;
    }
}

Did I do something wrong with consume?Or the problem occured when produce message?

**Comment by edenhill** [comment] 2015-11-07 07:19
Could you provide a complete buildable program?
Thanks

**Comment by edenhill** [comment] 2015-11-07 07:32
I think the problem is this issue: https://github.com/edenhill/librdkafka/issues/227

In essence it is currently not allowed to call stop+start in quick succession.
This is fixed on the oct15 branch and will be merged to master within a month.

**Comment by jimmy1911** [comment] 2015-11-07 09:22
Thank you for your fast response!I pull oct15 branch, but it can not be compiled successfully.

**Comment by edenhill** [comment] 2015-11-07 09:42
oct15 is in alpha state, but it should compile. Could you provide the compiler output?

**Comment by edenhill** [comment] 2015-11-07 09:58
And I want to thank you for providing a test program (even though a bit incomplete). That is very useful.

**Comment by jimmy1911** [comment] 2015-11-07 11:26
The compiler output:
make[1]: Leaving directory `/home/workspace/src/librdkafka/src-cpp'
make -C examples
make[1]: Entering directory `/home/workspace/src/librdkafka/examples'
gcc -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith  -I../src rdkafka_example.c -o rdkafka_example  \
		../src/librdkafka.a -lpthread -lz   -lssl -lcrypto   -lrt
../src/librdkafka.a(snappy.o): In function `find_lsb_set_non_zero64':
/home/workspace/src/librdkafka/src/snappy.c:177: undefined reference to `rd_ctz64'
collect2: ld returned 1 exit status
make[1]: *** [rdkafka_example] Error 1
make[1]: Leaving directory `/home/workspace/src/librdkafka/examples'
make: *** [examples] Error 2

And I will provide a test program later.You are so hard working!

**Comment by jimmy1911** [comment] 2015-11-08 06:31
I commited a test program to https://github.com/jimmy1911/librdkafka/tree/master/tests/rdkafka_offset_test.  rdkafka_offset_test is independent project including librdkafka's *.h *.a . You can make and run it . The testcase is described in https://github.com/jimmy1911/librdkafka/blob/master/tests/rdkafka_offset_test/README.md. 

TestCase1:produce 10000 messages, consume 1000, it is all OK.
set produce_num = 10000
set consume_num=1000
consume with the right offset

TestCase2:produce 100000 messages, consume 1000, it is wrong.
set produce_num = 100000
set consume_num=1000
consume with wrong offset, the log is  liks this:
#################################################
consume topic:kafka_test_10000 par_id:0 offset:1
Read msg at offset 30594
msg_20594
consume topic:kafka_test_10000 par_id:0 offset:2
Read msg at offset 2
msg_2
consume topic:kafka_test_10000 par_id:0 offset:3
consume topic:kafka_test_10000 par_id:0 offset:4
Read msg at offset 3
msg_3
consume topic:kafka_test_10000 par_id:0 offset:5
Read msg at offset 5
msg_5
consume topic:kafka_test_10000 par_id:0 offset:6
Read msg at offset 30598
msg_20598
################################################

**Comment by jimmy1911** [comment] 2015-11-09 03:03
@edenhill  have  you verified  my test program?

**Comment by edenhill** [comment] 2015-11-09 09:08
Which version of librdkafka is your program failing on?

**Comment by jimmy1911** [comment] 2015-11-09 09:24
The newest version on master branch, and its git sha is  3e1babf4f26a7d12bbd272c1cdf4aa6a44000d4a.

**Comment by edenhill** [comment] 2015-11-09 09:41
Yes, that is bug #227, it is not fixed on master yet, only on oct15 branch (which is in alpha state)

**Comment by JoseReboredo** [comment] 2015-12-02 02:05
Hi,
I am trying to use your project and because of the way I am planning to use the consumers, I am facing this issue. Do you plan to merge the branch 15_oct in master soon? It would help me a lot. Thank you!

**Comment by edenhill** [comment] 2015-12-02 07:53
0.9.0 will be released within a couple of weeks with a fix for this

**Comment by edenhill** [comment] 2015-12-14 21:42
Fixed on master

**Closed by edenhill** 2015-12-14 21:42 UTC
Labels: consumer, duplicate
