### ISSUE TITLE
No EOF event emitted with kafka broker 2.0.0

### ISSUE THREAD

**Issue by shanson7** [edenhill/librdkafka#2803] opened 2020-04-07 13:36 UTC
Description
===========
When using librdkafka 1.3.0 with broker 1.1.0 and I get all of the expected EOF events. With broker 2.0.0 I never get `ERR__PARTITION_EOF`. Per advice from Magnus, I added 1isolation.level=read_uncommitted` and that did the trick. As requested, I am submitting this issue with debug logging.

How to reproduce
================
Set `enable.partition.eof=true` and consume to the end of a partition against a 2.0 broker. 

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `1.3.0`
 - [x] Apache Kafka version: `2.0.0`
 - [x] librdkafka client configuration: ``
 - [x] Operating system: `centos 7`
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka - logs with `debug=fetch,msg`
[slidr.log.read_commit.cleaned.txt](https://github.com/edenhill/librdkafka/files/4444678/slidr.log.read_commit.cleaned.txt)
[slidr.log.read_uncommit.cleaned.txt](https://github.com/edenhill/librdkafka/files/4444679/slidr.log.read_uncommit.cleaned.txt)

 - [] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment] 2020-04-09 15:38
Reproduced this on AK 2.0.0, but not reproducible on 2.4.0, so this seems to be a broker issue.

**Comment by edenhill** [comment] 2020-04-09 16:01
Seems to be fixed in 2.0.1, but not finding anything overly obvious in the release notes:
https://archive.apache.org/dist/kafka/2.0.1/RELEASE_NOTES.html

Possibly this https://issues.apache.org/jira/browse/KAFKA-7128

**Comment by edenhill** [comment] 2020-04-09 16:01
Workaround client-side is to set `isolation.level=read_uncommitted`

**Closed by edenhill** 2020-04-09 16:01 UTC
