### ISSUE TITLE
105 errno, errinfo No buffe space available

### ISSUE THREAD

**Issue by wangyanshun** [edenhill/librdkafka#925] opened 2016-11-28 13:40 UTC
Description
===========

The config “queue.buffering.max.messages ” value is 400000, and librdkafka version is the latest release 0.9.2.

I Want to known the queue buffer is a gloable share queue or a single queue for each topic ?

 After I upgrade the libradkafka from 0.8.2 to 0.9.2, it offten print the log "errno 105, No buffer space availble."

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [0.9.2 ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ “queue.buffering.max.messages ”  = 400000] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment] 2016-11-28 13:44
The setting is global.
You can verify this value by calling rd_kafka_outq_len() which should show something similar.

**Comment by wangyanshun** [comment] 2016-11-28 14:19
I read your example, I found you will call rd_kafka_poll  after each rd_kafka_produce,  is it must be done?

**Comment by edenhill** [comment] 2016-11-28 14:21
No, you can call poll() whenever you want, but you should do it frequently enough.
`queue.buffering.max.messages` does not only account for messages that are queued for transmission to the broker, it also accounts for delivery reports enqueued for the application and they are served by `rd_kafka_poll()`.

**Comment by wangyanshun** [comment] 2016-11-28 14:30
So, after I  called rd_kafka_produce, I should call rd_kafka_poll  every time . Is It ?

Even if I do not care the  reports information, I should call rd_kafka_poll to consum the data in the gloable queue. Is It ?

**Comment by edenhill** [comment] 2016-11-28 14:31
You typically either call poll(0) after each produce() call, or you have a main loop somewhere that calls it, or you have a separate thread that calls it (poll(1000)).

If you dont care about delivery reports (which you should if delivery status matters to you) you can simply not register a dr_cb/dr_msg_cb (or any callback for that matter).
In this case you dont have to call poll() at all.

**Comment by wangyanshun** [comment] 2016-11-28 14:39
Another Question.
Dose it  the report information queue share the same queue with the data queue that are queued for transmission to the broker ?

My Producer Use Case Like This, And I not register a dr_cb/dr_msg_cb.

int excuteProducer(string & topic, int partition, const string& ctx)
{
    int res;
    rd_kafka_topic_t *rkt = NULL;

    rkt = rd_kafka_topic_new(rk, topic.c_str(), NULL);
    if(NULL == rkt)
    {
    
        return -1;
    }
    res = rd_kafka_produce(rkt, partition, RD_KAFKA_MSG_F_COPY, const_cast<char*>(ctx.c_str()), ctx.size(), NULL, 0, NULL);

   // I should call ??
  rd_kafka_poll() ??

    rd_kafka_topic_destroy(rkt);

    if(res == -1)
    {
       
        return -1;
    }

   
    return GSE_SUCCESS;
}

**Comment by edenhill** [comment] 2016-11-28 14:44
Yes, outq_len() accounts both for messages waiting to be produced as well as delivery reports, but if you have not registered a delivery report callback they will not be counted.

Your example looks fine.
On an unrelated note I want to hint you of the new rd_kafka_producev() call that allows you to specify the topic as a string to avoid having to instantiate a topic_t object for each call:
https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.h#L2454

Example usage:
https://github.com/edenhill/librdkafka/blob/master/tests/0052-msg_timestamps.c#L79

It is available on master and will be in the next release (0.9.3)

**Comment by wangyanshun** [comment] 2016-11-28 15:08
Thanks for your suggestion, I will upgrade the 0.9.3 when it arrived.

**Comment by wangyanshun** [comment] 2016-12-04 11:19
About the report information, I have some questions.
First, In the Top Level section,  what the msg_cnt means ? 
Second, In the brokers section, what the outbuf_msg_cnt means ?
Third, In the partitions section, what the msgq_cnt  means ?

Although you had explained the fileds, but I would like you to explain more details about those fileds.

In my use case, I offen got the 105 error code . To fix it, I got the reports when 105 error happens.

I sum all partitions msg_cnt , and the result value means the top level msg_cnt value, but some time   the result is small.

Please help me , Thanks.

**Comment by edenhill** [comment] 2016-12-04 19:04
See this link for stats:
https://github.com/edenhill/librdkafka/wiki/Statistics

**Comment by wangyanshun** [comment] 2016-12-12 10:59
@edenhill , I often get  the  105 error.  
I already set the msseage queue max count is 1000000, but the error has not been fixed.

I got the report stats , please give me some suggestions about how to fix it.
`

[kafka_stats.txt](https://github.com/edenhill/librdkafka/files/645739/kafka_stats.txt)

`

**Comment by wangyanshun** [comment] 2016-12-13 09:00
After  I  upgraded the librdkafka from v0.8.2   to v0.9.2,  the rd_kafka_produce function often return the  105 error code .

**Comment by edenhill** [comment] 2016-12-13 09:50
You have 1M messages (and 725Mb) in internal producer queues awaiting transmission to brokers:
```
$ cat kafka_stats.txt | jq -s 'map(.topics[].partitions[].msgq_cnt) | add'
1000000
$ cat kafka_stats.txt | jq -s 'map(.topics[].partitions[].msgq_bytes) | add'
725855819
```

The reason they are held in partition queues is that there are no leaders for your partitions:
```
$ cat kafka_stats.txt | jq '.topics[].partitions[].leader' | grep -v ^-1
$
```

You can query the broker for leaders with rdkafka_example or kafkacat using `kafkacat -b <broker> -L -t PlayerLogin393`.
Also check broker logs.

**Comment by wangyanshun** [comment] 2016-12-13 10:09
If there is not leader for any partitions, it will send nothing , is it ?

**Comment by edenhill** [comment] 2016-12-13 10:18
exactly, it will queue messages internally until a leader is available or the message times out.

**Comment by wangyanshun** [comment] 2016-12-13 10:20
If the message times out,  the message will be lost ? or will be resend ?

What is the condition， which will make the partition leader switch ?

When the server return the 105 error code, It will keep a long time and  can not  be fixed by its own.

**Comment by wangyanshun** [comment] 2016-12-13 10:23
If I send the message to the broker ,when the leader is un available, What will be happen?

**Comment by edenhill** [comment] 2016-12-13 10:29
Your delivery report callback will be called with an error when the message times out.

Check your broker logs to find out why there is no leader for your partitions.

Producer will queue messages internally until a leader is available or the message times out.

**Comment by wangyanshun** [comment] 2016-12-13 11:23
As far as I know， the partition‘s leader are consist in the metadata .Once the metadata information update , the partition's leader information  will be updated as the same time.

In that case，the partition's  leader information should be right. But now, the information was lost, I thought that the reason they are not fetched and was cleaned by rdlibkafka's metadata information update logic code  internally, is it ? 

If the partition leader information loss,  it must be to get the information from broker is like this，the partition no leader.

**Comment by edenhill** [comment] 2016-12-13 11:41
Can you use rdkafka_example or kafkacat do extract the topic metadata listing?
`rdkafka_example -b <broker> -L`

Do they all have leaders? (not -1)

If so, please reproduce the bad behaviour in librdkafka with `debug=metadata,topic` enabled

**Comment by wangyanshun** [comment] 2016-12-13 11:53
Yes, I am using it. Next get error 105 ,I will catch the metadata.
Thanks.

**Comment by wangyanshun** [comment] 2016-12-13 14:58
how to reproduce ?

**Comment by wangyanshun** [comment] 2016-12-29 07:53
I known the reason.

The librdkafka 0.9.2 and kafka server 0.8.2.1 collocation is used, if the  topics from the metadata in the request contain a illegal topic which will cause the kafka server 0.8.2.1 end to all the topic of the metadata processing of the request, and returns an error, the librdkafka 0.9.2 received the response from kafka server and clear the local topic partition leader.

**Closed** 2017-01-03 13:18 UTC
