### ISSUE TITLE
Different errors a consumer can encounter

### ISSUE THREAD

**Issue by rathdeep** [edenhill/librdkafka#416] opened 2015-11-10 16:00 UTC
Let’s say I am using rd_kafka_consume_callback, I get error  rd_kafka_consume_callback() == -1. Now what are the different possible scenarios of errors (like all brokers are down, or leader went down and librdkafka got error, in next attempt we got a new leader and consume succeeded, local queue is full).

I don’t want to lose any message. Basically if there is any fatal error which could lead to any message being missed, I want to stop my application. or all brokers for a topic go down.

Could not see any error handling in "rdkafka_performance.c". So this question.

Thanks.

**Comment by edenhill** [comment] 2015-11-10 17:22
`rd_kafka_consume_callback()` will only return -1 if you pass it an invalid topic+partition combo that you previously have not started consumption for.
Otherwise it returns the number of message callbacks called.

Typically librdkafka hides any non-permanent errors from the application and handles them gracefully internally by retrying.
Permanent errors are handled in different ways:
 * global errors, e.g., all brokers down, are passed to the error_cb and served through `rd_kafka_poll()`  (RD_KAFKA_RESP_ERR__ALL_BROKERS_DOWN).
 * Producer: message delivery failures (and success) are passed to the dr_cb/dr_msg_cb callback and served through `rd_kafka_poll()`
* Consumer: Consumer errors, such as mild notifications (PARTITION_EOF) or more serious errors are passed as `rkmessage->err` for the .._consume*() functions that return or pass an rd_kafka_message_t.

This means that a producer application should be calling rd_kafka_poll() every now and then, and a consumer application should both consume messages (duh..) and call rd_kafka_poll() every now and then.

**Comment by rathdeep** [comment] 2015-11-11 06:52
Thanks. Regarding PARTITION_EOF, lets say we have 1000 messages on  topic + partition on broker side. And local q size on librdkafka is 500. Hope we rcv PARTITION_EOF after reading 1000 msgs from broker and not once 500 msgs are consumed from local q.

RD_KAFKA_RESP_ERR__ALL_BROKERS_DOWN: Will we get this even when all leaders for a topic + partition are down or only when all brokers for a cluster are down (i.e. all topics + partitions are down).

So, for Producer, if brokers are down, rd_kafka_produce call might not fail. It  might succeed and in message delivery callback, we will be informed  of failure ?

**Comment by edenhill** [comment] 2015-11-11 06:59
PARTITION_EOF will be posted on the queue when the current last message of a partition has been received. Depending on the produce and consume rate this could happen frequently. (Thus it is not really an error, just a notification)

ALL_BROKERS_DOWN: when all broker connections are down. There is currently no notification when just the leaders are down.

Your last statement is true. librdkafka will hold on to a produce()d message for message.timeout.ms, trying to get it delivered.

**Comment by rathdeep** [comment] 2015-11-11 07:03
So PARTITION_EOF is not for the partition which resides on broker. It marks EOF of local queue which resides on librdkafka.

**Comment by edenhill** [comment] 2015-11-11 07:07
No, it is when we reach the end of the broker's partition, but that is a moving target naturally.

**Comment by rathdeep** [comment] 2015-11-11 07:09
Ok cool. So in my above example, we will rcv EOF only after 1000 msgs (provided no msgs produced after that) and not before that.

**Comment by rathdeep** [comment] 2015-11-11 07:10
Also on consumer side, won't calling rd_kafka_consume_callback every now and then should suffice. As that will call msg_consume which has rkmessage->err. Why we need to additionally call rd_kafka_poll.

**Comment by edenhill** [comment] 2015-11-11 07:16
Correct.

Global errors that are not tied to a particular consume instance, are propagated through rd_kafka_poll().
 That's why you should call both.
If you dont care about the global errors you dont need to call poll (but you must not set up any error_cb then)

**Comment by rathdeep** [comment] 2015-11-11 07:23
Ok. Only if i setup error_cb  or stat_cb, i should call rd_kafka_poll() to get these callbacks.

Lets say in my consumer, i am setting only rd_kafka_consume_callback and not any other callback., so there is no point of calling rd_kafka_poll.rd_kafka_poll is not for rd_kafka_consume_callback. Hope my understanding is correct.

**Comment by edenhill** [comment] 2015-11-11 07:26
Correct

Den 11 nov 2015 08:23 skrev "rathdeep" <notifications@github.com>:
>
> Ok. Only if i setup error_cb or stat_cb, i should call rd_kafka_poll() to
get these callbacks.
>
> Lets say in my consumer, i am setting only rd_kafka_consume_callback and
not any other callback., so there is no point of calling
rd_kafka_poll.rd_kafka_poll is not for rd_kafka_consume_callback. Hope my
understanding is correct.

**Comment by rathdeep** [comment] 2015-11-13 14:28
I was going thru  your article "https://github.com/edenhill/librdkafka/wiki/Consuming-from-multiple-topics-partitions-from-a-single-thread"

Regarding following statement. Does librdkafka has its internal synchronization in place when reading from multiple partitions of same topic. Lets say a application creates 2 threads to read from same topic plus different partition and just print the count of messages (so no sync required from application perspective). In this case, does application need to take care of any synchronization for librdkafka ? 

"but when consuming from multiple partitions of the same topic multiple application threads complicate matters and requires the application to perform the usual lock-and-dispatch queue between threads"

**Comment by rathdeep** [comment] 2015-11-13 14:41
Similar question:
The librdkafka consumer queue is unique per topic + partition combination or unique for a topic rd_kafka_topic_new.
E.g. I create 2 rd_kafka_topic_new() handles for same topic + partition (use case could be 2 threads consuming different kind of data from same topic + partition). Will I receive all the messages twice or only once.

**Comment by edenhill** [comment] 2015-11-13 14:43
Internally there is one message queue per partition, so if you do consume(topic, partition,..) for the same topic and partition from two different threads simultaneously you will not see the same messages on both threads.

librdkafka is thread-safe so it is safe for an application to call any of its functions from any thread (unless otherwise noted).
This allows you to consume from different threads.

**Comment by edenhill** [comment] 2015-11-13 14:44
If you are using the queue interface (consume_start_queue()..) then all messages will end up in the same queue. This queue might still be served from multiple application threads though, if that makes sense to the application.

**Comment by rathdeep** [comment] 2015-11-13 14:46
"Internally there is one message queue per partition, so if you do consume(topic, partition,..) for the same topic and partition from two different threads simultaneously you will not see the same messages on both threads."

So this will be the behavior even if i create multiple rd_kafka_topic_new() handles for same topic + partition.

Thanks for the clarification.

**Comment by edenhill** [comment] 2015-11-13 15:01
if you look at the returned pointer from topic_new() you will see they are the same.
Matching topic objects are reused.

**Comment by rathdeep** [comment] 2015-11-14 10:56
A different topic regarding error handling.. It will be good if  application can check whether a kafka handle rd_kafka_new() or topic rd_kafka_topic_new is valid at any point of time via some librdkafka API call. And then act based on that..

**Comment by rathdeep** [comment] 2015-11-14 11:38
Coming back to the original topic, I am consuming from 2 partitions  (say 1, 2) of same topic. Now at any point of time, i would like to stop consuming from any one partition 1. Now i want to cleanup all resources for partition 1 basically the internal q created for partition 1. I cannot delete topic as it is being used to read partition 2. Whats the best to handle this. i call rd_kafka_consume_stop(rkt, 1) to stop consuming, but want to make sure either Q for partition 1 is deleted or all messages from that Q is consumed.

**Comment by edenhill** [comment] 2015-11-14 15:09
The topic handle is refcounted so you should call topic_new() and topic_destroy() symetrically.
Only when the refcount reaches 0 will the topic be removed.
(due to internal design the topic will never be destroyed, but you dont need to know that)

Calling consume_stop() will drain the local queue of fetched messages for that partition only.

**Comment by rathdeep** [comment] 2015-11-14 15:23
Thanks. just read this comment
* Stop consuming messages for topic 'rkt' and 'partition', purging
 * all messages currently in the local queue.

Does this hold true for shared q approach too, https://github.com/edenhill/librdkafka/wiki/Consuming-from-multiple-topics-partitions-from-a-single-thread

Will rd_kafka_consume_stop  purge records from rkqu for that partition.  rkqu will have the messages in mixed order from various partitions.

**Comment by edenhill** [comment] 2015-11-14 15:29
It currently does not purge the partition's messages in shared queue, but the next version of librdkafka will do that.

Also keep in mind that the current version of librdkafka has problems with quickly doing stop()+start(), so I suggest you dont do that.

**Comment by rathdeep** [comment] 2015-11-14 15:34
whats the issue.. also earlier i faced issue.. will reconfirm
i read from start_offset 100. read 100, 101, 102. Then stop and start from 100 again. but get from 103 onwards.

**Comment by rathdeep** [comment] 2015-11-14 15:37
Also regarding your comment, "problems with quickly doing stop()+start()" , is there any workaround like giving some sleep between stop and start.

**Comment by edenhill** [comment] 2015-11-14 15:46
The problem is that stop() is asynchronous, it will return immediately but librdkafka needs to perform some operations in the background (such as writing offset to offset storage, etc).
If start() is called before those background ops are finished it is undefined what offset will be used.

There is no "known good" sleep interval, you'll just have to try and see what works.

This will be fixed in the next release (in a couple of weeks).

**Comment by rathdeep** [comment] 2015-11-19 15:32
Will handles returned by rd_kafka_new and rd_kafka_topic_new remain valid after permanent errors are resolved.

Let says All brokers go down. Will librdkafka reconnect once brokers are up.  And will old rd_kafka_new and rd_kafka_topic_new still remain valid or application needs to create new rd_kafka_new and rd_kafka_topic_new.

**Comment by edenhill** [comment] 2015-11-19 15:48
An application typically will not have to care about connectivity to the brokers, rdkafka will take care of that and  topics and configuration will persist across lost connections.

**Comment by rathdeep** [comment] 2015-11-21 11:24
when   rd_kafka_consume_stop(rkt, partition) can fail if i am calling stop  after rd_kafka_consume_start(rkt, partition).

Will rd_kafka_consume_stop fail if temporarily broker is down or any other error. When broker is up or error is recovered, will earlier call of rd_kafka_consume_stop will take care of stop Or does application need to call rd_kafka_consume_stop again.

**Comment by edenhill** [comment] 2015-11-22 11:21
_stop() will not fail and it is not allowed to call it multiple times (without start() inbetween).

The new consumer API that will be released within a month works a bit differenty and will have a consumer_close() call that will block until all background operations are finished, such as offset commits.

**Comment by rathdeep** [comment] 2015-12-07 15:48
On consumer stop/start from an offset, I am not receiving the end of partition message sometimes.
On consumer side, I am not storing offset in file.
First I consume from 2 (topic + partition)  (topic is same) using rd_kafka_consume_start( with offset).
Then call stop  on both partitions and wait for quite some time (30 secs) for cleanup.
Using same topic, I start consuming again from same 2 topic + partitions with offset. There is only one data on  one partition. But rd_kafka_consume_callback returns only 1. It should have returned 2 ( 1 one data, one for endofpartition).    Any known issues ?

Thanks.

**Comment by edenhill** [comment] 2015-12-07 18:54
Quick stop()+start() are broken in master, try using the 0.9.0 branch and the new rd_kafka_seek() API.

**Comment by rathdeep** [comment] 2015-12-07 19:40
As topic handle is reused,  I think even destroying topic and recreating
won't help.. ?
Wht do u mean by quick. I can wait for a minute too.. I want to use this
feature in production,  so want the official release...

On Tuesday, December 8, 2015, Magnus Edenhill <notifications@github.com>
wrote:
> Quick stop()+start() are broken in master, try using the 0.9.0 branch and
the new rd_kafka_seek() API.
>
> —
> Reply to this email directly or view it on GitHub.<
https://ci4.googleusercontent.com/proxy/XHAs29HB9RUy5kRvhzBtqvf1Xi7Ewzlbq8LYjEd8Dg7ezr800qBA8XGdJxsuSFiyIbJ9g3UhcMjpxGVw2Tjf12XMltqaRPxoCRnFHzhoGDE9mOMKfscnytOJ-d751Vf7mZsdpk24eD6Kd_I2DQ_0_sN6MNPd0Q=s0-d-e1-ft#https://github.com/notifications/beacon/AMiknPsjrih6pg8UCAgRtruGJqlVuR_tks5pNc2JgaJpZM4Gfhre.gif
>

**Comment by rathdeep** [comment] 2015-12-11 12:09
Does  0.9.0 needs new Kafka broker version too.

**Comment by edenhill** [comment] 2015-12-11 12:15
librdkafka 0.9.0 is backwards compatible with 0.8 brokers, but the new high-level KafkaConsumer interface requires 0.9 brokers.

**Closed by edenhill** 2015-12-11 12:15 UTC
Labels: question

**Comment by zpeng2022** [comment] 2024-09-19 02:59
> _stop() will not fail and it is not allowed to call it multiple times (without start() inbetween).
> 
> The new consumer API that will be released within a month works a bit differenty and will have a consumer_close() call that will block until all background operations are finished, such as offset commits.

hi， edenhill
I have previously tried calling consume_stop multiple times. Is there any detailed documentation explaining these points to note?

thanks.
