### ISSUE TITLE
[Question] OffsetCommitCb clarification

### ISSUE THREAD

**Issue by coberty** [edenhill/librdkafka#1684] opened 2018-02-14 11:00 UTC
Hello,
I have a few questions regarding OffsetCommitCb.
I'm using librdkafka-0.9.5. 

1. Is there a way to check which offset/partition current callback call is refering to?
I can see only ERR_NO_ERROR. Offsets vector is empty. Is the vector filled only when error happens?

2. How can I force a commit error? I'd like to test how it reacts when error occurs.

3. Is the callback called for every commit call? Let's say I called commitAsync 10k times. Does it mean the callback would be also called 10k times or some grouping might happen as well?

Thanks,
cob

**Comment by edenhill** [comment] 2018-02-14 11:06
answers:
 1. if you get a commit_cb() with no offsets it means there were no offsets to commit, this can happen if yu call commit() for offsets that have already been committed. 
 2. Good question, you could try passing an invalid partition, e.g. (123456)
 3. It is called for each commit

I suggest you upgrade to librdkafka 0.11.3, there's been a number of fixes to the consumer since 0.9.5

**Comment by coberty** [comment] 2018-02-14 13:30
Thanks.
As to the 1. - I'm using commitAsync(message) method. Does it work for this method in the same way? I'm getting ERR_NO_ERROR and empty vector on each commit.

**Comment by edenhill** [comment] 2018-02-14 13:31
Can you reproduce on master or 0.11.3?

**Comment by coberty** [comment] 2018-02-15 14:52
It's some project misconfiguration on my side. It's working in release mode, not working in debug...

**Closed** 2018-02-22 09:16 UTC
