### ISSUE TITLE
commitAsync() crash in VS2015 debug win32 build

### ISSUE THREAD

**Issue by szmcdull** [edenhill/librdkafka#983] opened 2017-01-05 12:14 UTC
Description
===========
Strange crash occurs in VS2015 debug win32 build.
In file rdkafka_offset.c at line 423, rd_kafka_commit(): 
        err = rd_kafka_commit0(rk, offsets, NULL,
			       !async ? RD_KAFKA_REPLYQ(repq, 0) :
			       RD_KAFKA_NO_REPLYQ, NULL, NULL);

The compiler seems got confused and calls RD_KAFKA_REPLYQ when async == 1. The crash ran away after i modified the code as below:
        if (!async)
            err = rd_kafka_commit0(rk, offsets, NULL,
                RD_KAFKA_REPLYQ(repq, 0), NULL, NULL);
        else
            err = rd_kafka_commit0(rk, offsets, NULL,
                RD_KAFKA_NO_REPLYQ, NULL, NULL);

How to reproduce
================
call RdKafka::KafkaConsumer::commitAsync() on a successfully fetched Message

Checklist
=========
Please provide the following information:

 - [0.9.2] librdkafka version (release number or git tag):
 - [0.10.1.1] Apache Kafka version: 
 - [auto.commit=false] librdkafka client configuration:
 - [Windows 7/10 64 bit] Operating system:
 - [ ] Using the legacy Consumer
 - [X] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment] 2017-01-05 14:06
Thanks for finding the root cause, much appreciated.

There was a similar report some time ago where the combination of ternary operator and temporary struct instances didn't play well together on AIX, iirc.
https://github.com/edenhill/librdkafka/pull/852

So I believe this issue should be fixed in master, can you give it a spin?

**Closed** 2017-01-05 14:07 UTC
Labels: duplicate

**Comment by szmcdull** [comment] 2017-01-06 03:46
Yes, master works :)
