### ISSUE TITLE
Event callback was not called when connections are resumed

### ISSUE THREAD

**Issue by jupiterh** [edenhill/librdkafka#875] opened 2016-10-31 00:46 UTC
# Description

Hi,

I have an eventCallback class inherited from RdKafka::EventCb, it got event callback when the connection was down or server was down, but it did not get event when the connection was resumed. I don't want to run this->producer->produce until I can make sure that the connection is ok. Is it the normal behaviour of the RdKafka::EventCb or did I miss something here?

Thank you.
# How to reproduce
# Checklist

Please provide the following information:
- [ ] librdkafka version (release number or git tag):
- [ ] Apache Kafka version: 
- [ ] librdkafka client configuration:
- [ ] Operating system:
- [ ] Using the legacy Consumer
- [ ] Using the high-level KafkaConsumer
- [ ] Provide logs (with `debug=..` as necessary) from librdkafka
- [ ] Provide broker log excerpts
- [ ] Critical issue

**Comment by edenhill** [comment] 2016-11-02 08:29
To quote https://github.com/edenhill/librdkafka/blob/master/INTRODUCTION.md#message-reliability
> This [broker failure] is handled automatically by librdkafka and the application does not need to take any action at any of the above events. The message will be resent up to "message.send.max.retries" times before reporting a failure back to the application.

**Comment by edenhill** [comment] 2016-11-03 20:26
There is currently no non-debug log or event to indicate that the connection is back up.

Duplicate of #137

**Closed by edenhill** 2016-11-03 20:26 UTC
Labels: duplicate
