### ISSUE TITLE
Broker connection dies because HEARTBEAT is delayed behind fetching many partitions on Windows

### ISSUE THREAD

**Issue by JonECG** [edenhill/librdkafka#1821] opened 2018-05-24 23:19 UTC
Description
===========
I've noticed an issue on Windows when being assigned many partitions during a rebalance that the connection will die because of delayed heartbeats. Essentially the heartbeat will be enqueued as an `XMIT_BUF` op but will sit behind thousands of `WAKEUP` ops that repeatedly interrupt op processing on the broker, preventing the heartbeat from being processed in a timely manner. With default settings I see this consistently at 10000 partitions, but with a more aggressive session timeout and heartbeat interval I've sometimes seen this at 1000 partitions.

I've added some additional op-related logging categories to help show the flow (`BUFENQUEUEASOP`, `BUFENQUEUEFROMOP`, `OPENQUEUE`, `OPSERVE`) and ignored `OFFSET` and `OFFSETFETCH`, as they were very noisy.

```
431376125 RECV: [thrd:localhost:9092/bootstrap]: localhost:9092/1001: Received OffsetResponse (v0, 33 bytes, CorrId 111, rtt 73.93ms)
431376125 RECV: [thrd:localhost:9092/bootstrap]: localhost:9092/1001: Received OffsetResponse (v0, 33 bytes, CorrId 112, rtt 73.93ms)
431376125 BUFENQUEUEASOP: [thrd:main]: localhost:9092/1001: Enqueuing rkbuf with xmit op with api key Heartbeat
431376125 RECV: [thrd:localhost:9092/bootstrap]: localhost:9092/1001: Received OffsetResponse (v0, 33 bytes, CorrId 113, rtt 73.92ms)
431376125 OPENQUEUE: [thrd:main]: localhost:9092/1001: Enqueuing op XMIT_BUF
431376125 RECV: [thrd:localhost:9092/bootstrap]: localhost:9092/1001: Received OffsetResponse (v0, 33 bytes, CorrId 114, rtt 73.93ms)
431376125 OPENQUEUE: [thrd:main]: localhost:9092/1001: Enqueuing op WAKEUP
431376125 WAKEUP: [thrd:main]: localhost:9092/1001: Wake-up
431376125 RECV: [thrd:localhost:9092/bootstrap]: localhost:9092/1001: Received OffsetResponse (v0, 33 bytes, CorrId 115, rtt 73.93ms)
431376125 OPENQUEUE: [thrd:main]: localhost:9092/1001: Enqueuing op WAKEUP
431376125 WAKEUP: [thrd:main]: localhost:9092/1001: Wake-up
...
<102 seconds later>
...
431478569 OPSERVE: [thrd:localhost:9092/bootstrap]: localhost:9092/1001: Serving op WAKEUP
431478572 OPSERVE: [thrd:localhost:9092/bootstrap]: localhost:9092/1001: Serving op WAKEUP
431478576 OPSERVE: [thrd:localhost:9092/bootstrap]: localhost:9092/1001: Serving op WAKEUP
431478579 OPSERVE: [thrd:localhost:9092/bootstrap]: localhost:9092/1001: Serving op WAKEUP
431478583 OPSERVE: [thrd:localhost:9092/bootstrap]: localhost:9092/1001: Serving op WAKEUP
431478586 OPSERVE: [thrd:localhost:9092/bootstrap]: localhost:9092/1001: Serving op WAKEUP
431478590 OPSERVE: [thrd:localhost:9092/bootstrap]: localhost:9092/1001: Serving op XMIT_BUF
431478590 BUFENQUEUEFROMOP: [thrd:localhost:9092/bootstrap]: localhost:9092/1001: Enqueuing rkbuf from serving xmit op with api key Heartbeat
431478590 SEND: [thrd:localhost:9092/bootstrap]: localhost:9092/1001: Sent HeartbeatRequest (v0, 78 bytes @ 0, CorrId 10265)
431478668 RECV: [thrd:localhost:9092/bootstrap]: localhost:9092/1001: Received FetchResponse (v4, 300019 bytes, CorrId 10264, rtt 820.66ms)
431478672 RECV: [thrd:localhost:9092/bootstrap]: localhost:9092/1001: Received HeartbeatResponse (v0, 2 bytes, CorrId 10265, rtt 81.32ms)
431478672 HEARTBEAT: [thrd:main]: Group "group" heartbeat error response in state up (join state started, 10000 partition(s) assigned): Broker: Unknown member
431478672 MEMBERID: [thrd:main]: Group "group": updating member id "rdkafka-7f322d16-1f6c-43d8-b96a-046e7a5ba349" -> ""
431478672 CGRPJOINSTATE: [thrd:main]: Group "group" changed join state started -> init (v4, state up)
431478678 SEND: [thrd:localhost:9092/bootstrap]: localhost:9092/1001: Sent FetchRequest (v4, 160053 bytes @ 0, CorrId 10266)
431478678 CGRPJOINSTATE: [thrd:main]: Group "group" changed join state init -> wait-unassign (v4, state up)
```
And on the broker:
```
kafka_1      | [2018-05-24 21:37:59,200] INFO [GroupCoordinator 1001]: Preparing to rebalance group group with old generation 0 (__consumer_offsets-47) (kafka.coordinator.group.GroupCoordinator)
kafka_1      | [2018-05-24 21:37:59,213] INFO [GroupCoordinator 1001]: Stabilized group group generation 1 (__consumer_offsets-47) (kafka.coordinator.group.GroupCoordinator)
kafka_1      | [2018-05-24 21:38:01,266] INFO [GroupCoordinator 1001]: Assignment received from leader for group group for generation 1 (kafka.coordinator.group.GroupCoordinator)
kafka_1      | [2018-05-24 21:38:01,328] INFO Updated PartitionLeaderEpoch. New: {epoch:0, offset:0}, Current: {epoch:-1, offset-1} for Partition: __consumer_offsets-47. Cache now contains 0 entries. (kafka.server.epoch.LeaderEpochFileCache)
kafka_1      | [2018-05-24 21:38:38,036] INFO [GroupCoordinator 1001]: Member rdkafka-a9ab5790-6019-4c76-bd0b-4a097ff27f6b in group group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
kafka_1      | [2018-05-24 21:38:38,036] INFO [GroupCoordinator 1001]: Preparing to rebalance group group with old generation 1 (__consumer_offsets-47) (kafka.coordinator.group.GroupCoordinator)
kafka_1      | [2018-05-24 21:38:38,041] INFO [GroupCoordinator 1001]: Group group with generation 2 is now empty (__consumer_offsets-47) (kafka.coordinator.group.GroupCoordinator)
```

How to reproduce
================
1. Start the kafka cluster with a lot of partitions per topic (10000)
In the attached project I've included a docker compose that can be ran with `docker-compose -f docker-compose-kafka.yml up`

2. Build the attached project with Visual Studio 2017

3. Run the built application
`consumer.exe <brokers> <topic> <debug>`
default brokers: "localhost:9092"
default topic: "topic"
default debug: "cgrp,protocol,queue"

4. Observe in the kafka log that the group loses a member from lack of heartbeats while the application handles the `WAKEUP`s and gets an error when it finally does send the hearbeat before trying to rejoin.

It seems to have stemmed from this change https://github.com/edenhill/librdkafka/commit/fc482dccebf3b742cb309b0c450879cc0041c5e7 which recently introduced the behavior of `WAKEUP` ops interrupting the op queue, which doesn't play nicely with each partition fetch also spawning a `WAKEUP` op.

I've implemented a workaround that only allows one `WAKEUP` op to be enqueued at a time which remedies the heartbeat failure. To enable the workaround, set `LIBRDKAFKA_WAKEUP_WORKAROUND=1` in the rdkafka project properties in Visual Studio under _Configuration Properties > C/C++ > Preprocessor > Preprocessor Definitions_ and rebuild/run. Notice that it joins the group cleanly and the connection stays alive.

However, I'm not sure if having multiple ops that interrupt the op queue is an intended behavior or would affect the ongoing effort for supporting on-demand connections. If that's the case, perhaps the `WAKEUP` op could be refcounted and requeue itself if there are refs remaining when being served. I think it might also be worth exploring having a preemptive high-priority op queue for `HEARTBEAT`s, even a flag on the broker will do, to prevent heartbeats from being backed up behind other requests (ops or send buffers).

If you have any issues building, I have also included prebuilt binaries with and without the workaround and the logs associated with them. I've also included the patch for the workaround against 653afd4c014dc51841f1fee40b0f0ef6be071563.

Attachments
=========
[LibrdkafkaHeartbeatFailureRepro.zip](https://github.com/edenhill/librdkafka/files/2037257/LibrdkafkaHeartbeatFailureRepro.zip) - Includes repro project, prebuilt binaries and logs, and docker compose script
[librdkafka_workaround.txt](https://github.com/edenhill/librdkafka/files/2037261/librdkafka_workaround.txt) - git patch file of workaround allowing only one enqueued `WAKEUP` op at a time against 653afd4c014dc51841f1fee40b0f0ef6be071563

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): affects `v0.11.4`, tested against 653afd4c014dc51841f1fee40b0f0ef6be071563
 - [x] Apache Kafka version: `1.0.0`
 - [x] librdkafka client configuration: `debug=cgrp,protocol,queue;metadata.broker.list=localhost:9092;group.id=group`
 - [x] Operating system: `Windows 10 Version 10.0.16299 Build 16299; VS2017 Pro Version 15.5.6`
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka: *See above and attached*
 - [x] Provide broker log excerpts:  *See above*
 - [ ] Critical issue **(workaround provided)**

**Comment by edenhill** [comment] 2018-05-25 06:08
Wow, this is an amazing bug report!

**Comment by edenhill** [comment] 2018-05-25 06:09
`<102 seconds later>`
Does that mean 102 seconds of nothing, or 102 seconds of something else?

**Comment by JonECG** [comment] 2018-05-25 17:34
Thanks! It means 102 seconds of a lot of logs that I didn't want to post inline. It's an excerpt of the full log set that I had previously hidden in the attached zip, my apologies. The full logs are too large uncompressed, so here they are individually zipped.

The full log that contains the excerpt from above: [consumer_no_workaround.zip](https://github.com/edenhill/librdkafka/files/2040353/consumer_no_workaround.zip)
In contrast, logs from with the workaround: [consumer_with_workaround.zip](https://github.com/edenhill/librdkafka/files/2040366/consumer_with_workaround.zip)

**Comment by edenhill** [comment] 2018-06-16 00:01
I think the problem is that WAKEUP makes broker_op_serve() return 0, telling the caller to not keep looping over it, which should infact only be used with the TERMINATE op.

**Comment by JonECG** [comment] 2018-06-19 17:49
I've noticed this as well. It looked like an explicit change for https://github.com/edenhill/librdkafka/pull/1667 so I wasn't sure if the behavior was intentional (That wakeup would stop op processing to immediately work on processing the network).

**Comment by edenhill** [comment] 2018-07-05 15:33
Fixed on master

**Closed by edenhill** 2018-07-05 15:33 UTC
Labels: GREAT REPORT
