### ISSUE TITLE
Windows - Broker transport failure: (errno: No error)

### ISSUE THREAD

**Issue by harishmk** [edenhill/librdkafka#516] opened 2016-01-24 19:15 UTC
Seeing this with the latest source code. Looks like the error happens during metadata refresh.
Here is the full log with `debug=all`
[KafkaProducer_20160124 - Copy (2).txt](https://github.com/edenhill/librdkafka/files/102502/KafkaProducer_20160124.-.Copy.2.txt)

```
2016-01-24 14:06:09.296063|0x0000472c|info|gg::lqs::kafka::KafkaProducer::event_cb|KafkaProducer.cpp:363 BROKERFAIL: localhost:9092/bootstrap: failed: err: Local: Broker transport failure: (errno: No error)
2016-01-24 14:06:09.296063|0x0000472c|error|gg::lqs::kafka::KafkaProducer::event_cb|KafkaProducer.cpp:363 FAIL: localhost:9092/bootstrap: Connection closed
2016-01-24 14:06:09.302064|0x0000472c|info|gg::lqs::kafka::KafkaProducer::event_cb|KafkaProducer.cpp:363 STATE: localhost:9092/bootstrap: Broker changed state UP -> DOWN
2016-01-24 14:06:09.303065|0x0000472c|info|gg::lqs::kafka::KafkaProducer::event_cb|KafkaProducer.cpp:363 BUFQ: localhost:9092/bootstrap: Purging bufq with 0 buffers
2016-01-24 14:06:09.303065|0x0000472c|info|gg::lqs::kafka::KafkaProducer::event_cb|KafkaProducer.cpp:363 METADATA: NJ1MTLAPP01.wanlink.us:9092/0: Request metadata for locally known topics: leader query
2016-01-24 14:06:09.303065|0x0000472c|info|gg::lqs::kafka::KafkaProducer::event_cb|KafkaProducer.cpp:363 METADATA: NJ1MTLAPP01.wanlink.us:9092/0: Request metadata: scheduled: not in broker thread
2016-01-24 14:06:09.303065|0x0000472c|info|gg::lqs::kafka::KafkaProducer::event_cb|KafkaProducer.cpp:363 CONNECT: localhost:9092/bootstrap: broker in state DOWN connecting
2016-01-24 14:06:09.304065|0x0000472c|info|gg::lqs::kafka::KafkaProducer::event_cb|KafkaProducer.cpp:363 CONNECT: localhost:9092/bootstrap: Connecting to ipv4#127.0.0.1:9092 (plaintext) with socket 324
2016-01-24 14:06:09.303065|0x00007444|error|gg::lqs::kafka::KafkaProducer::event_cb|KafkaProducer.cpp:363 Error event: -195: Local: Broker transport failure - localhost:9092/bootstrap: Connection closed
2016-01-24 14:06:09.312066|0x0000472c|info|gg::lqs::kafka::KafkaProducer::event_cb|KafkaProducer.cpp:363 STATE: localhost:9092/bootstrap: Broker changed state DOWN -> CONNECT
2016-01-24 14:06:09.322068|0x0000472c|info|gg::lqs::kafka::KafkaProducer::event_cb|KafkaProducer.cpp:363 CONNECT: localhost:9092/bootstrap: Connected to ipv4#127.0.0.1:9092
2016-01-24 14:06:09.322068|0x0000472c|info|gg::lqs::kafka::KafkaProducer::event_cb|KafkaProducer.cpp:363 CONNECTED: localhost:9092/bootstrap: Connected
```

**Comment by edenhill** [comment] 2016-01-24 19:32
Looks like the broker is disconnecting the producer.  What does the broker log say?

**Comment by harishmk** [comment] 2016-01-24 19:40
nothing of significance at around the time when the disconnect was reported:
```
[2016-01-24 12:56:48,635] INFO [Group Metadata Manager on Broker 0]: Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.GroupMetadataManager)
[2016-01-24 13:06:48,665] INFO [Group Metadata Manager on Broker 0]: Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.GroupMetadataManager)
[2016-01-24 13:16:48,694] INFO [Group Metadata Manager on Broker 0]: Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.GroupMetadataManager)
[2016-01-24 13:26:48,724] INFO [Group Metadata Manager on Broker 0]: Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.GroupMetadataManager)
[2016-01-24 13:36:49,568] INFO [Group Metadata Manager on Broker 0]: Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.GroupMetadataManager)
[2016-01-24 13:46:49,766] INFO [Group Metadata Manager on Broker 0]: Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.GroupMetadataManager)
[2016-01-24 13:56:49,856] INFO [Group Metadata Manager on Broker 0]: Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.GroupMetadataManager)
[2016-01-24 14:06:49,946] INFO [Group Metadata Manager on Broker 0]: Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.GroupMetadataManager)
[2016-01-24 14:16:50,036] INFO [Group Metadata Manager on Broker 0]: Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.GroupMetadataManager)
[2016-01-24 14:26:50,125] INFO [Group Metadata Manager on Broker 0]: Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.GroupMetadataManager)
[2016-01-24 14:36:50,215] INFO [Group Metadata Manager on Broker 0]: Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.GroupMetadataManager)
```

**Comment by edenhill** [comment] 2016-01-24 19:43
Is this happening ten minutes after program startup?
Could be the (0.9) broker idle connection closer acting.

**Comment by harishmk** [comment] 2016-01-24 19:55
seems to be periodic:
```
2016-01-24 08:56:58.773506|0x000022a4|error|gg::lqs::kafka::KafkaProducer::event_cb|KafkaProducer.cpp:363 FAIL: localhost:9092/bootstrap: Connection closed
2016-01-24 08:56:58.787507|0x00002a60|error|gg::lqs::kafka::KafkaProducer::event_cb|KafkaProducer.cpp:363 Error event: -195: Local: Broker transport failure - localhost:9092/bootstrap: Connection closed
2016-01-24 09:11:58.862496|0x000022a4|error|gg::lqs::kafka::KafkaProducer::event_cb|KafkaProducer.cpp:363 FAIL: localhost:9092/bootstrap: Connection closed
2016-01-24 09:11:58.877498|0x00002a60|error|gg::lqs::kafka::KafkaProducer::event_cb|KafkaProducer.cpp:363 Error event: -195: Local: Broker transport failure - localhost:9092/bootstrap: Connection closed
2016-01-24 09:21:59.078507|0x000022a4|error|gg::lqs::kafka::KafkaProducer::event_cb|KafkaProducer.cpp:363 FAIL: localhost:9092/bootstrap: Connection closed
2016-01-24 09:21:59.090508|0x00002a60|error|gg::lqs::kafka::KafkaProducer::event_cb|KafkaProducer.cpp:363 Error event: -195: Local: Broker transport failure - localhost:9092/bootstrap: Connection closed
2016-01-24 09:36:59.021492|0x00002a24|error|gg::lqs::kafka::KafkaProducer::event_cb|KafkaProducer.cpp:363 FAIL: IL1TSTLQSAPP01.wanlink.us:9092/0: Connection closed
2016-01-24 09:36:59.034494|0x00002a60|error|gg::lqs::kafka::KafkaProducer::event_cb|KafkaProducer.cpp:363 Error event: -195: Local: Broker transport failure - IL1TSTLQSAPP01.wanlink.us:9092/0: Connection closed
2016-01-24 09:46:59.146499|0x00002a24|error|gg::lqs::kafka::KafkaProducer::event_cb|KafkaProducer.cpp:363 FAIL: IL1TSTLQSAPP01.wanlink.us:9092/0: Connection closed
2016-01-24 09:46:59.163500|0x00002a60|error|gg::lqs::kafka::KafkaProducer::event_cb|KafkaProducer.cpp:363 Error event: -195: Local: Broker transport failure - IL1TSTLQSAPP01.wanlink.us:9092/0: Connection closed
2016-01-24 09:56:59.422423|0x00002a24|error|gg::lqs::kafka::KafkaProducer::event_cb|KafkaProducer.cpp:363 FAIL: IL1TSTLQSAPP01.wanlink.us:9092/0: Connection closed
2016-01-24 09:56:59.432425|0x00002a60|error|gg::lqs::kafka::KafkaProducer::event_cb|KafkaProducer.cpp:363 Error event: -195: Local: Broker transport failure - IL1TSTLQSAPP01.wanlink.us:9092/0: Connection closed
2016-01-24 10:31:59.393571|0x000022a4|error|gg::lqs::kafka::KafkaProducer::event_cb|KafkaProducer.cpp:363 FAIL: localhost:9092/bootstrap: Connection closed
2016-01-24 10:31:59.403573|0x00002a60|error|gg::lqs::kafka::KafkaProducer::event_cb|KafkaProducer.cpp:363 Error event: -195: Local: Broker transport failure - localhost:9092/bootstrap: Connection closed
2016-01-24 10:46:59.425467|0x000022a4|error|gg::lqs::kafka::KafkaProducer::event_cb|KafkaProducer.cpp:363 FAIL: localhost:9092/bootstrap: Connection closed
2016-01-24 10:46:59.436468|0x00002a60|error|gg::lqs::kafka::KafkaProducer::event_cb|KafkaProducer.cpp:363 Error event: -195: Local: Broker transport failure - localhost:9092/bootstrap: Connection closed
2016-01-24 11:01:59.536893|0x000022a4|error|gg::lqs::kafka::KafkaProducer::event_cb|KafkaProducer.cpp:363 FAIL: localhost:9092/bootstrap: Connection closed
2016-01-24 11:01:59.547896|0x00002a60|error|gg::lqs::kafka::KafkaProducer::event_cb|KafkaProducer.cpp:363 Error event: -195: Local: Broker transport failure - localhost:9092/bootstrap: Connection closed
2016-01-24 11:11:59.732469|0x00002a24|error|gg::lqs::kafka::KafkaProducer::event_cb|KafkaProducer.cpp:363 FAIL: IL1TSTLQSAPP01.wanlink.us:9092/0: Connection closed
2016-01-24 11:11:59.746470|0x00002a60|error|gg::lqs::kafka::KafkaProducer::event_cb|KafkaProducer.cpp:363 Error event: -195: Local: Broker transport failure - IL1TSTLQSAPP01.wanlink.us:9092/0: Connection closed
2016-01-24 11:46:59.853450|0x00002a24|error|gg::lqs::kafka::KafkaProducer::event_cb|KafkaProducer.cpp:363 FAIL: IL1TSTLQSAPP01.wanlink.us:9092/0: Connection closed
2016-01-24 11:46:59.866452|0x00002a60|error|gg::lqs::kafka::KafkaProducer::event_cb|KafkaProducer.cpp:363 Error event: -195: Local: Broker transport failure - IL1TSTLQSAPP01.wanlink.us:9092/0: Connection closed
2016-01-24 12:01:59.794436|0x000022a4|error|gg::lqs::kafka::KafkaProducer::event_cb|KafkaProducer.cpp:363 FAIL: localhost:9092/bootstrap: Connection closed
2016-01-24 12:01:59.806437|0x00002a60|error|gg::lqs::kafka::KafkaProducer::event_cb|KafkaProducer.cpp:363 Error event: -195: Local: Broker transport failure - localhost:9092/bootstrap: Connection closed
2016-01-24 12:21:59.943438|0x00002a24|error|gg::lqs::kafka::KafkaProducer::event_cb|KafkaProducer.cpp:363 FAIL: IL1TSTLQSAPP01.wanlink.us:9092/0: Connection closed
2016-01-24 12:21:59.950439|0x00002a60|error|gg::lqs::kafka::KafkaProducer::event_cb|KafkaProducer.cpp:363 Error event: -195: Local: Broker transport failure - IL1TSTLQSAPP01.wanlink.us:9092/0: Connection closed
2016-01-24 12:36:59.975433|0x00002a24|error|gg::lqs::kafka::KafkaProducer::event_cb|KafkaProducer.cpp:363 FAIL: IL1TSTLQSAPP01.wanlink.us:9092/0: Connection closed
2016-01-24 12:36:59.990434|0x00002a60|error|gg::lqs::kafka::KafkaProducer::event_cb|KafkaProducer.cpp:363 Error event: -195: Local: Broker transport failure - IL1TSTLQSAPP01.wanlink.us:9092/0: Connection closed
2016-01-24 12:52:00.107318|0x000022a4|error|gg::lqs::kafka::KafkaProducer::event_cb|KafkaProducer.cpp:363 FAIL: localhost:9092/bootstrap: Connection closed
2016-01-24 12:52:00.119321|0x00002a60|error|gg::lqs::kafka::KafkaProducer::event_cb|KafkaProducer.cpp:363 Error event: -195: Local: Broker transport failure - localhost:9092/bootstrap: Connection closed
2016-01-24 13:02:00.378430|0x000022a4|error|gg::lqs::kafka::KafkaProducer::event_cb|KafkaProducer.cpp:363 FAIL: localhost:9092/bootstrap: Connection closed
2016-01-24 13:02:00.390431|0x00002a60|error|gg::lqs::kafka::KafkaProducer::event_cb|KafkaProducer.cpp:363 Error event: -195: Local: Broker transport failure - localhost:9092/bootstrap: Connection closed
2016-01-24 13:42:00.449413|0x000022a4|error|gg::lqs::kafka::KafkaProducer::event_cb|KafkaProducer.cpp:363 FAIL: localhost:9092/bootstrap: Connection closed
2016-01-24 13:42:00.463414|0x00002a60|error|gg::lqs::kafka::KafkaProducer::event_cb|KafkaProducer.cpp:363 Error event: -195: Local: Broker transport failure - localhost:9092/bootstrap: Connection closed
2016-01-24 13:57:00.509710|0x000022a4|error|gg::lqs::kafka::KafkaProducer::event_cb|KafkaProducer.cpp:363 FAIL: localhost:9092/bootstrap: Connection closed
2016-01-24 13:57:00.522713|0x00002a60|error|gg::lqs::kafka::KafkaProducer::event_cb|KafkaProducer.cpp:363 Error event: -195: Local: Broker transport failure - localhost:9092/bootstrap: Connection closed
2016-01-24 14:07:00.653399|0x000022a4|error|gg::lqs::kafka::KafkaProducer::event_cb|KafkaProducer.cpp:363 FAIL: localhost:9092/bootstrap: Connection closed
2016-01-24 14:07:00.666401|0x00002a60|error|gg::lqs::kafka::KafkaProducer::event_cb|KafkaProducer.cpp:363 Error event: -195: Local: Broker transport failure - localhost:9092/bootstrap: Connection closed
2016-01-24 14:17:00.731401|0x000022a4|error|gg::lqs::kafka::KafkaProducer::event_cb|KafkaProducer.cpp:363 FAIL: localhost:9092/bootstrap: Connection closed
2016-01-24 14:17:00.743402|0x00002a60|error|gg::lqs::kafka::KafkaProducer::event_cb|KafkaProducer.cpp:363 Error event: -195: Local: Broker transport failure - localhost:9092/bootstrap: Connection closed
2016-01-24 14:27:00.862408|0x000022a4|error|gg::lqs::kafka::KafkaProducer::event_cb|KafkaProducer.cpp:363 FAIL: localhost:9092/bootstrap: Connection closed
2016-01-24 14:27:00.879410|0x00002a60|error|gg::lqs::kafka::KafkaProducer::event_cb|KafkaProducer.cpp:363 Error event: -195: Local: Broker transport failure - localhost:9092/bootstrap: Connection closed
```

**Comment by edenhill** [comment] 2016-01-24 19:57
I think those times look suspiciously close to 10 minutes (or more in the case where the connection is used for metadata updates).
Search for `connections.max.idle.ms` here:http://kafka.apache.org/documentation.html

You can disable the logging of connection close with `log.connection.close=false` in librdkafka.

Duplicate of issue #437

**Closed by edenhill** 2016-01-24 19:57 UTC
