### ISSUE TITLE
Working fine on 0.9.1 but failed to run from the Master: "Invalid value type" 

### ISSUE THREAD

**Issue by jupiterh** [edenhill/librdkafka#1058] opened 2017-02-14 01:13 UTC
Description
===========
Hi Edenhill,

As per your advice I tried to test master code which will reduce the overheads, my code was running fine under 0.9.1, but could not run under the master library, it was an error of invalid value type of event call back in my statement set("event_cb", &this->event, errorString) != RdKafka::Conf::CONF_OK where this->event is a class object EventCallback event, it was complied fine under master library but failed to run. What could I be missing here?

calss EventCallback : public RdKafka::EventCb {
  .....
};

Thank you

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment] 2017-02-14 01:27
This was just fixed in commit https://github.com/edenhill/librdkafka/commit/a3a6dbea78042e6efa6af5e08464cbf20eaec607

Which version are you on?

**Comment by jupiterh** [comment] 2017-02-14 02:38
I made a clone from git@github.com:edenhill/librdkafka.git yesterday, let me update and try it again. Thanks Edenhill.

**Comment by jupiterh** [comment] 2017-02-14 05:12
Thanks Edenhill, that issue has been fixed, 

But I could not run my program, it got SEGFAULT when it ran to the statement RdKafka::Topic *topic = RdKafka::Topic::create(producer, topic_str, tconf, errstr) with Master library, are there any build environment changes since 0.9.1? My program works with 0.9.1, also it was built from Debian Jessie ARM environment

**Comment by edenhill** [comment] 2017-02-14 19:19
Can you run your program with gdb to find out the cause of the crash?

**Comment by jupiterh** [comment] 2017-02-14 23:17
Yes, I did. It stopped at TopicImpl.cpp:112, but every address was legal, I could not see why, may be you could give some clues:

Program received signal SIGSEGV, Segmentation fault.
0xb6624f76 in RdKafka::Topic::create (base=0x10238c, topic_str="EventTopic", conf=0x103880, 
    errstr="") at TopicImpl.cpp:112
(gdb) print *(base)
$1 = {_vptr.Handle = 0xb663c8f0 <vtable for RdKafka::ProducerImpl+232>}
(gdb) print topic_str
$2 = "EventTopic"
(gdb) print conf
$3 = (RdKafka::Conf *) 0x103880
(gdb) print base
$4 = (RdKafka::Handle *) 0x10238c

**Comment by jupiterh** [comment] 2017-02-15 23:16
Hi Edenhill,

Any insight about the signal SIGILL at TopicImpl.cpp:112 in the master? Thank you.

**Comment by edenhill** [comment] 2017-02-16 02:18
Did you try to recompile your program with an updated librdkafka?
It might be an ABI compatibility issue if you are using an app compiled for an earlier version of librdkafka. This should work but might be the issue

**Comment by jupiterh** [comment] 2017-02-16 08:21
Yes, I did. I am aware of incompatibility issue.

If that does not work, i have to use the 0.9.1, but that version generated large overhead even the consumer is not used. Is there anyway to change configure parameters in rdkafka_conf.c to disable prefetch and metadata for consumer in 0.9.1?

Thank you very much.

**Comment by edenhill** [comment] 2017-02-16 15:49
@jupiterh So even after recompiling your app using a newer version of librdkafka it crashes when you call Topic::create()?

Can you paste the relevant code in your application that sets up the config and Kafka and topic objects?

**Comment by jupiterh** [comment] 2017-02-17 03:45
Hi Edenhill,

Here is the snippet of the code crashed at the line of library API RdKafka::Topic::create, you can refer to my previous comments and debug, all input parameters of the function are valid. The this->producer is pointing to std::shared_ptr<RdKafka::Producer> producer, the this->TopicConfig() is pointing to std::shared_ptr<RdKafka::Conf> topicConfig, I can ensure you those values are initialized and all valid.
 
RdKafka::Topic *rawTopic = RdKafka::Topic::create(this->producer.get(), this->getConfig().topicTitle, this->getTopicConfig().get(), errorString);
if (rawTopic) {
     this->setTopic(std::shared_ptr<RdKafka::Topic>(rawTopic));
}

It was always running fine with 0.9.1 librdkafka++.so.1 but crashed at the same line in master librdkafka++.so.1 TopicImpl.cpp:112.

**Closed** 2017-02-23 02:06 UTC

**Comment by edenhill** [comment] 2017-02-23 08:14
@jupiterh did you find the issue?

**Comment by edenhill** [comment] 2017-02-23 10:16
Dup of #1075
