### ISSUE TITLE
Purge brokers no longer reported in metadata

### ISSUE THREAD

**Issue by skandragon** [edenhill/librdkafka#238] opened 2015-04-09 18:08 UTC
Scenario:

* Start up a topic where some partitions are on broker 0, some are on broker 1
* Move the partitions to a single broker (0)
* Kill broker 1, as it is no longer relevant to the topics currently in service

You will get this sort of log (from the example consumer in this case):

* 1428602624.709 RDKAFKA-3-FAIL: rdkafka#consumer-0: 10.42.0.144:9092/1: Failed to connect to broker at 10.42.0.144:9092: Operation timed out
* 1428602624.709 RDKAFKA-3-ERROR: rdkafka#consumer-0: 10.42.0.144:9092/1: Failed to connect to broker at 10.42.0.144:9092: Operation timed out
* 1428602625.715 RDKAFKA-3-FAIL: rdkafka#consumer-0: 10.42.0.144:9092/1: Failed to connect to broker at 10.42.0.144:9092: Host is down
* 1428602625.715 RDKAFKA-3-ERROR: rdkafka#consumer-0: 10.42.0.144:9092/1: Failed to connect to broker at 10.42.0.144:9092: Host is down
* 1428602718.698 RDKAFKA-3-FAIL: rdkafka#consumer-0: 10.42.0.144:9092/1: Failed to connect to broker at 10.42.0.144:9092: Operation timed out
* 1428602718.698 RDKAFKA-3-ERROR: rdkafka#consumer-0: 10.42.0.144:9092/1: Failed to connect to broker at 10.42.0.144:9092: Operation timed out

Producers also do this.

**Comment by edenhill** [comment] 2015-04-09 19:57
There are two reasons it is a bit noisy in this particular case:
* The duplicated messages are because error events are automatically translated into log messages if no `error_cb` is registered, and rdkafka_example does not register an error_cb.
* Multiple sub-sequent broker failures with the same error will be silenced internally, but if the error changes, like in this case (Host is down and Operation timed out), the logs will be emitted. The `Host is down` message should typically only occur on locally connected servers where ARP times out (iirc).

This is to say that this specific scenario might not be a typical error scenario.

I'm not really sure what to do with this, I dont want to stop trying to connect to a down broker, it could be temporarily down for a number of reasons.
What could be added is an API for removing brokers, but I'm not sure the application will know so much better.

**Comment by skandragon** [comment] 2015-04-09 20:09
In this case though, the broker in question no longer services any topics I created.  It seems like the library should not need to connect to those anymore.

**Comment by edenhill** [comment] 2015-04-09 20:10
Is it still included in Metadata from other brokers? (when requesting metadata for all topics)

**Comment by skandragon** [comment] 2015-04-10 15:51
I don't think so.  Restarting the consumer or producer causes it to no longer attempt to connect, but the non-restarted processes will continue trying.

**Comment by edenhill** [comment] 2015-04-14 19:56
librdkafka does not forget about learnt brokers even if they are removed from the broker metadata listing.
The reasoning behind this is to recover from partitioning where the cluster splits up, rdkafka has contact with side B that stops advertising side A brokers. Then B goes down and A becomes available again.
In this case, if the A brokers were removed when B stopped reporting them, then rdkafka would not be able to connect back to A.

So I thought it best not to remove any learnt broker.

**Comment by edenhill** [comment] 2015-04-19 06:35
Are you happy with this explanation?

**Comment by yyejun** [comment] 2015-04-20 23:31
If broker ids are randomly assigned, Old brokers are replaced by new brokers with different ids during software/hardware upgrade. The broker list for meta query can behind a load balance proxy.

Under this situation seems it will be better have a way to forget old brokers.

**Comment by edenhill** [comment] 2015-04-21 07:03
Could add a configuration property to remove brokers that have not been up for a certain configured time.
Would this be enough?

**Comment by skandragon** [comment] 2015-04-22 18:16
Can the metadata just be refreshed, and then not-current ones forgotten automatically?

**Comment by edenhill** [comment] 2015-04-22 20:39
@skandragon See this comment on why they persist:
https://github.com/edenhill/librdkafka/issues/238#issuecomment-93040674

**Comment by skandragon** [comment] 2015-05-01 21:48
If you added the auto-remove option, that would likely be sufficient for my uses. All I want to do is eventually stop spamming the logs about a dead broker that no longer has relevance.

**Comment by skandragon** [comment] 2015-05-01 21:53
I'm also not expecting perfection here.  If we can use the currently in-use topics to indicate which brokers are no longer relevant as they are not currently in use by any of them, then they can be ignored from that point on automatically as well.  Holding on to stale data just in case it may become useful seems less robust than dropping known irrelevant and likely stale data.

Another option would be to do some sort of reasonable back-off, rather than retrying pretty frequently.  The messages are operationally distracting; I want my logs filled with relevant errors, not ones that I know no longer matter but the system disagrees, even though the metadata for the topic does agree.

**Comment by edenhill** [comment] 2015-05-06 11:22
Unfortunately in a split brain scenario there is no authoritative answer, and thus no "known irrelevant"s.

But what should be done is:
 * silence brokers that aren't available. There should preferably only be one single log message for a broker that goes away indefinately.
 * Remove brokers that haven't been seen in metadata for a certain configured time interval. This should be off by default.
 * Additionally, use sparse connections. Currently all brokers are connected to (and queried for metadata), this provides robustness.  With a new option to use sparse connections only the brokers we actually need to connect to (leaders for topic+partitions and consumer groups) will be connected to. The initial bootstrap broker could be purged as well.

**Comment by yyejun** [comment] 2015-05-06 17:42
Because zookeeper itself cannot be split. So if on the side of the network has no zookeeper connection, those kafka brokers will be not be able to serve metadata either.

**Comment by edenhill** [comment] 2015-05-07 08:59
@yyejun you are right, so librdkafka could be more aggressive in purging no-longer-announced brokers.

**Comment by edenhill** [comment] 2016-10-07 07:15
Duplicate of #825

**Closed by edenhill** 2016-10-07 07:15 UTC
Labels: duplicate, enhancement
