### ISSUE TITLE
Topic binary-chunks partition count changed from 2 to 0

### ISSUE THREAD

**Issue by skandragon** [edenhill/librdkafka#237] opened 2015-04-09 16:25 UTC
This message happened when I did these steps:

* Created a two-partition topic, with replication factor of 1
* added a second broker
* moved the topic to be balanced across each broker (partition 0 -> broker 0, 1 -> 1)
* This message was then generated on a client that remained connected.

From this point on, it seems the producer only used topic 0 (the one which did not move from one broker to another from its point of view)

Killing the producer triggers some "drain" code we have in place, which will report the number of messages left to send:

info: still waiting to send 16 kafka messages

It looks like librdkafka lost its connection to partition 1, but continued to try to use it, queueing messages and lost them forever for the topic that was changed.

**Comment by edenhill** [comment] 2015-04-09 17:22
Thanks for the detailed fault scenario.

Did you happen to get a metadata listing for the topic after the new broker was added?
(i.e., with kafkacat -L  or kafka-topics.sh --describe)

**Comment by skandragon** [comment] 2015-04-09 18:03
I can describe that, but I think we are running into another issue as well there.  The metadata is really, really unreliable.

In summary:  ISRS shows only one broker as up to date, but they both actually are.  Killing one or the other causes the ISRS to change to that one broker.  Since the metadata is unreliable, I'm not sure how much we can actually rely on what it says.

**Comment by edenhill** [comment] 2015-04-09 20:01
The ISR in the Metadata is indeed unreliable, which is a bug in Kafka, so it cannot be trusted.
See this issue: https://issues.apache.org/jira/browse/KAFKA-1367

But the partition count and Leader lists should be reliable.

**Comment by skandragon** [comment] 2015-04-09 20:10
In all cases, other than ISR data, the leader and topic was otherwise healthy.

**Comment by edenhill** [comment] 2015-04-09 20:24
Did you stop&start broker 0 when adding broker 1?
Did you use kafka-reassign-partitions.sh to move partition 1 to broker 1?

**Comment by skandragon** [comment] 2015-04-10 15:05
I added broker 1, then used the reassign script to move partition 1 to broker 1.  I did not restart broker 0.

**Comment by edenhill** [comment] 2015-04-14 19:53
Okay. Is this easily reproducible?

**Comment by skandragon** [comment] 2015-04-17 21:17
I think the notes I sent in the opening message would do it.  :)

**Comment by edenhill** [comment] 2015-09-08 21:30
It seems that a broker may return partitionCnt == 0 if ErrorCode > 0 for a topic with partitions but that lacks a current leader for any topic, which seems to be an intermittent problem.
The oct15 branch solves this by not shrinking rdkafka's partition count for the topic if the metadata contains an error code for the topic.

**Comment by edenhill** [comment] 2015-12-14 21:34
Fixed on master

**Closed by edenhill** 2015-12-14 21:34 UTC
Labels: bug, close on merge
