### ISSUE TITLE
Consumers can't commit offset but keep consuming

### ISSUE THREAD

**Issue by maesfreek** [edenhill/librdkafka#2214] opened 2019-02-01 15:58 UTC
Description
===========
We have around 80 consumers each with their own consumer group and topic. We have 3 brokers runnign on different machines, and 3 zookeeper nodes. 

We are running into problems where multiple consumers are unable to commit their offsets. The consumers keep consuming (for a while) but are unable to update their offset. They don't recover from this, neither do they crash hard.
Example from the consumer log:
```
%4|1549029124.064|COMMITFAIL|rdkafka#consumer-1| [thrd:main]: Offset commit (cgrp auto commit timer) failed for 3/3 partition(s): Local: Waiting for coordinator: x.y.intl[0]@191813685, x.y.intl[1]@195441157, x.y.intl[2]@196191784
```

This happens during normal operation, but also more frequently after a broker is restarted. Some potentially useful logs:
```
[2019-02-01 14:18:22,436] INFO [GroupMetadataManager brokerId=203] Finished unloading __consumer_offsets-48. Removed 0 cached offsets and 0 cached groups. (kafka.coordinator.group.GroupMetadataManager)
[2019-02-01 14:18:31,913] INFO [GroupCoordinator 203]: Member rdkafka-fcfa7488-5e5d-4f00-923c-ad595d0a1fb6 in group x-y@ds has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-02-01 14:18:31,913] INFO [GroupCoordinator 203]: Preparing to rebalance group x-y@ds in state PreparingRebalance with old generation 19 (__consumer_offsets-19) (reason: removing member rdkafka-fcfa7488-5e5d-4f00-923c-ad595d0a1fb6 on heartbeat e
xpiration) (kafka.coordinator.group.GroupCoordinator)
```

How to reproduce
================
Restart a broker manually, after some 10 minutes some consumers enter the state described above.

Checklist
=========
 - [x] librdkafka version (release number or git tag): `1.0.0`
 - [x] Apache Kafka version: `2.1.0`
 - [x] Scala version: `2.12`
 - [x] Kafkacat version: `1.3.0`
 - [x] librdkafka client configuration: 
```
socket.send.buffer.bytes=10485760
socket.receive.buffer.bytes=10485760
socket.request.max.bytes=104857600
queued.max.requests=1000
message.max.bytes=10000012
default.replication.factor=3
replica.fetch.max.bytes=10485760
message.max.bytes=10000000
linger.ms=5
num.partitions=3
retention.ms=1209600000
max.message.bytes=10000000
```
 - [x] Operating system: `Slackware`
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
 - [x] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment] 2019-02-05 09:12
v1.0.0 is not yet released and should only be used for testing.
This looks like a recent v1.0 regression that's fixed on the idempo_msg_tmouts branch (https://github.com/edenhill/librdkafka/commits/idempo_msg_tmouts) in commit https://github.com/edenhill/librdkafka/commit/cb4be1fc5158dd7502a46d7e1d43560a3c291700

**Closed** 2019-02-07 09:07 UTC
