### ISSUE TITLE
Consumer in 0.11 is very slow compared to 0.9.5

### ISSUE THREAD

**Issue by lalinsky** [edenhill/librdkafka#1385] opened 2017-08-19 11:36 UTC
Description
===========

The consumer code in 0.11.0 is very slow and uses a lot of network bandwidth compared to 0.9.5. I think there is some fundamental problem with the protocol handling. Below you can see a test with the included consumer example tool and a LZ4-compressed topic on Kafka 0.11.0.0. The first run on 0.9.5 is using about 40Mbps and averages around 30-40k messages per second. The second run on 0.11 is using the full network bandwidth (in my case 1Gbps) and only averages at around 300 messages per second.

```
llalinsky@imf-test-1:~/librdkafka-0.9.5$ ./examples/rdkafka_consumer_example -g tmp-llalinsky -b XXX:9092 -A XXX:9 | pv -l > /dev/null
% Assigning 1 partitions
91.8k 0:00:03 [37.2k/s]
 207k 0:00:05 [78.6k/s]
 305k 0:00:07 [30.7k/s]
% Consumer closed
llalinsky@imf-test-1:~/librdkafka-0.11.0$ ./examples/rdkafka_consumer_example -g tmp-llalinsky -b XXX:9092 -A XXX:9 | pv -l > /dev/null
% Assigning 1 partitions
2.26k 0:00:04 [ 307/s]
4.56k 0:00:12 [ 293/s]
 6.3k 0:00:17 [ 304/s]
% Consumer closed
```

How to reproduce
================

See the examples above. I was only able to reproduce the problem when reading from an old offset, so that there is a lot of data ahead.

**Comment by edenhill** [comment] 2017-08-21 15:37
And you are sure the latter run is not picking up from a previously committed offset?

**Comment by lalinsky** [comment] 2017-08-21 15:39
Yes, I'm sure. I modified the example to always start from offset 0 and I repeated it multiple times. The slow example is also using 1Gbps of network traffic, which it definitely should not if there was only 300 messages per second. :)

**Comment by edenhill** [comment] 2017-08-22 17:11
And I'm guessing you are seeing this lousy performance without piping to `pv` as well, yeah?

**Comment by lalinsky** [comment] 2017-08-24 15:38
Yes, that's how I discovered it. Using the example tool and pv are only for figuring out what's exactly slow.

Are you able to reproduce the behavior?

**Comment by edenhill** [comment] 2017-08-26 07:51
Can you reproduce this with `-d protocol,queue,broker`?

**Comment by kpocius** [comment] 2017-09-05 12:26
We seem to be having the same issue, but the behavior is very inconsistent - sometimes both versions work the same, sometimes one never manages to catch up. I'll work on narrowing it down to reproduce the issue more consistently and then apply the requested debug options.

**Comment by melnikov77** [comment] 2017-09-05 16:10
We have same issue, our test application is using 3Gbps but consumes just 10K messages/sec (message is very small just 20 bytes).
It looks like it always fetches 1 Mb of data but addes just few messages (20 bytes each) in local queue.
Here is a log:
7|2017-09-02 01:01:46.847|rdkafka#consumer-1|SEND| [thrd:10.90.18.5:9092/bootstrap]: 10.90.18.5:9092/2: Sent FetchRequest (v4, 74 bytes @ 0, CorrId 676)
7|2017-09-02 01:01:46.847|rdkafka#consumer-1|RECV| [thrd:10.90.18.5:9092/bootstrap]: 10.90.18.5:9092/2: Received FetchResponse (v4, 1048630 bytes, CorrId 676, rtt 0.00ms)
7|2017-09-02 01:01:46.847|rdkafka#consumer-1|FETCH| [thrd:10.90.18.5:9092/bootstrap]: 10.90.18.5:9092/2: Topic test-topic [0] MessageSet size 1048576, error "Success", MaxOffset 507304, Ver 2/2
7|2017-09-02 01:01:46.847|rdkafka#consumer-1|CONSUME| [thrd:10.90.18.5:9092/bootstrap]: 10.90.18.5:9092/2: Enqueue 10 message(s) on test-topic [0] fetch queue (qlen 10, v2, last_offset 37486)
7|2017-09-02 01:01:46.847|rdkafka#consumer-1|FETCH| [thrd:10.90.18.5:9092/bootstrap]: 10.90.18.5:9092/2: Fetch topic test-topic [0] at offset 37487 (v2)
7|2017-09-02 01:01:46.847|rdkafka#consumer-1|FETCH| [thrd:10.90.18.5:9092/bootstrap]: 10.90.18.5:9092/2: Fetch 1/1/3 toppar(s)
7|2017-09-02 01:01:46.847|rdkafka#consumer-1|SEND| [thrd:10.90.18.5:9092/bootstrap]: 10.90.18.5:9092/2: Sent FetchRequest (v4, 74 bytes @ 0, CorrId 677)
7|2017-09-02 01:01:46.862|rdkafka#consumer-1|RECV| [thrd:10.90.18.5:9092/bootstrap]: 10.90.18.5:9092/2: Received FetchResponse (v4, 1048630 bytes, CorrId 677, rtt 16.00ms)
7|2017-09-02 01:01:46.862|rdkafka#consumer-1|FETCH| [thrd:10.90.18.5:9092/bootstrap]: 10.90.18.5:9092/2: Topic test-topic [0] MessageSet size 1048576, error "Success", MaxOffset 507304, Ver 2/2
7|2017-09-02 01:01:46.862|rdkafka#consumer-1|CONSUME| [thrd:10.90.18.5:9092/bootstrap]: 10.90.18.5:9092/2: Enqueue 6 message(s) on test-topic [0] fetch queue (qlen 6, v2, last_offset 37492)
7|2017-09-02 01:01:46.862|rdkafka#consumer-1|FETCH| [thrd:10.90.18.5:9092/bootstrap]: 10.90.18.5:9092/2: Fetch topic test-topic [0] at offset 37493 (v2)
7|2017-09-02 01:01:46.862|rdkafka#consumer-1|FETCH| [thrd:10.90.18.5:9092/bootstrap]: 10.90.18.5:9092/2: Fetch 1/1/3 toppar(s)

**Comment by edenhill** [comment] 2017-09-05 16:17
@melnikov77 Weird, can you provide your consumer config?

**Comment by melnikov77** [comment] 2017-09-05 16:35
I tried different options, these one is latest:
"enable.auto.commit": false
"group.id": "test_group_1"
"queued.min.messages": 1_000_000
"socket.nagle.disable": true

**Comment by edenhill** [comment] 2017-09-05 18:34
Why are you disabling Nagle on the consumer? That would primarily be a producer thing

**Comment by melnikov77** [comment] 2017-09-05 21:29
I tried different options. Removing it doesn't change anything.

**Comment by edenhill** [comment] 2017-09-06 09:00
Okay, please reproduce with `debug=msg,protocol,fetch,topic,broker,queue` and provide me the logs, I want to find out why such a large message batch is resulting in only a few messages.
What is your typical message size?

**Comment by melnikov77** [comment] 2017-09-06 17:03
All messages have same size i.e.  ~25 bytes.

**Comment by melnikov77** [comment] 2017-09-06 17:40
Here is a link to download log file
[https://drive.google.com/open?id=0B4V6FxJ2JlZpYUUxVDlZc05tcG8](url)

**Comment by melnikov77** [comment] 2017-09-07 00:23
Here is log from older version (0.9.4) which work as expected (150K messages/sec from single partition)
[https://drive.google.com/open?id=0B4V6FxJ2JlZpNUk3enhUN2c2ZEU](url)

**Comment by edenhill** [comment] 2017-09-07 08:56
I believe this is a duplicate of #1384

**Closed** 2017-09-07 13:46 UTC
Labels: bug, consumer, duplicate
