### ISSUE TITLE
SSL Performance

### ISSUE THREAD

**Issue by pachacutec** [edenhill/librdkafka#788] opened 2016-09-09 13:54 UTC
Description
===========
 I am running the rdkafka_performance.c with SSL enable (client, broker), The perf values are reduced a lot, from 130M to 20M with SSL

Have you try with SSL? Could an hidden bug or we shall expect this behaviour?

How to reproduce
================
Generate the keys using https://github.com/edenhill/librdkafka/wiki/Using-SSL-with-librdkafka
Set Broker with SSL 
Run rdkafka_perfomance example with SSL

Checklist
=========
Please provide the following information:

 - [ X] librdkafka version (release number or git tag): 0.9.1
 - [ X] Apache Kafka version: 0.10.0.1
 - [ X] librdkafka client configuration: with SSL
 - [X ] Operating system: Linux Ubuntu
 - [ ] Using the legacy Consumer
 - [X ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ X] Critical issue

**Comment by edenhill** [comment] 2016-09-12 21:46
What CPU load are you seeing on the producer and broker when using SSL as compared to not using SSL?
Do you believe the bottleneck is in the producer or broker?

**Comment by pachacutec** [comment] 2016-09-13 01:12
The CPU when is on plaintext is 2% now 10%, I could not follow your code, but maybe could be the ssl handshake? I think could be the producer, but I am not sure.

this is cpu, net, io for an execution 


> ----system---- ----total-cpu-usage---- -dsk/total- --io/total- ---paging-- -net/total- ------memory-usage-----
     time     |usr sys idl wai hiq siq| read  writ| read  writ|  in   out | recv  send| used  buff  cach  free
13-09 01:04:29|  0   0 100   0   0   0| 105k   26k|4.77  1.99 |   0     0 |   0     0 | 653M 17.4M  178M 28.6G
13-09 01:04:34|  0   0 100   0   0   0|   0    19k|   0  1.20 |   0     0 | 729B 1251B| 653M 17.4M  178M 28.6G
13-09 01:04:39|  0   0 100   0   0   0|   0    22k|   0  2.00 |   0     0 |1831B 2516B| 653M 17.4M  178M 28.6G
13-09 01:04:44|  7   1  92   0   0   0|   0    26k|   0  2.00 |   0     0 | 185B  536B|2288M 17.4M  221M 27.0G
13-09 01:04:49| 13   2  85   0   0   0|   0    19k|   0  1.20 |   0     0 |  66B  456B|5575M 17.4M  337M 23.7G
13-09 01:04:54| 11   1  88   0   0   0|   0    40k|   0  4.40 |   0     0 |  66B  456B|7138M 17.4M  468M 22.0G
13-09 01:04:59| 10   1  90   0   0   0|   0    21k|   0  1.20 |   0     0 |  66B  456B|7143M 17.4M  620M 21.8G
13-09 01:05:04| 10   1  90   0   0   0|   0    19k|   0  1.20 |   0     0 |  66B  456B|7149M 17.4M  772M 21.7G
13-09 01:05:09| 10   0  90   0   0   0|   0    32k|   0  2.00 |   0     0 |  66B  456B|7152M 17.4M  925M 21.5G
13-09 01:05:14| 10   1  88   2   0   0|3277B   89M|0.80   720 |   0     0 |  77B  464B|7159M 17.4M 1076M 21.4G
13-09 01:05:19|  9   1  83   7   0   0|8192B  255M|2.00  2049 |   0     0 |  79B  511B|7163M 17.5M 1217M 21.2G
13-09 01:05:24|  9   1  87   3   0   0|1638B   65M|0.40   523 |   0     0 |  66B  472B|7167M 17.5M 1367M 21.1G
13-09 01:05:29| 10   1  90   0   0   0|   0    62k|   0  7.60 |   0     0 |  66B  457B|7171M 17.5M 1521M 20.9G
13-09 01:05:34| 10   0  90   0   0   0|   0    22k|   0  1.20 |   0     0 |  66B  456B|7175M 17.5M 1679M 20.8G
13-09 01:05:39| 10   1  90   0   0   0|   0    32k|   0  2.80 |   0     0 |  66B  456B|7181M 17.5M 1834M 20.6G
13-09 01:05:44| 10   0  90   0   0   0|   0    35k|   0  2.40 |   0     0 |  66B  456B|7185M 17.6M 1992M 20.5G
13-09 01:05:49| 10   0  90   0   0   0|   0    22k|   0  1.20 |   0     0 |  66B  456B|7189M 17.6M 2149M 20.3G
13-09 01:05:54| 10   1  82   8   0   0|4915B  225M|1.20  1804 |   0     0 |  79B  505B|7194M 17.6M 2305M 20.1G
13-09 01:05:59|  9   0  81   9   0   0|4915B  185M|1.20  1479 |   0     0 |  66B  472B|7198M 17.6M 2454M 20.0G
13-09 01:06:04| 10   0  90   0   0   0|   0    42k|   0  4.40 |   0     0 |  66B  459B|7202M 17.6M 2611M 19.8G
13-09 01:06:09| 10   0  90   0   0   0|   0    27k|   0  2.00 |   0     0 |  77B  464B|7206M 17.7M 2768M 19.7G
13-09 01:06:14| 10   1  90   0   0   0|   0    22k|   0  2.00 |   0     0 |  66B  456B|7211M 17.7M 2925M 19.5G
13-09 01:06:19| 10   1  89   0   0   0|   0    51k|   0  3.20 |   0     0 |  66B  456B|7220M 17.7M 3084M 19.4G
13-09 01:06:24| 10   1  88   2   0   0|3277B   80M|0.80   646 |   0     0 |  66B  459B|7221M 17.7M 3242M 19.2G
13-09 01:06:29|  9   1  79  12   0   0|8192B  255M|2.00  2044 |   0     0 |  79B  511B|7229M 17.7M 3391M 19.1G
13-09 01:06:34| 10   0  86   4   0   0|3277B   74M|0.80   595 |   0     0 |  66B  472B|7232M 17.8M 3551M 18.9G
13-09 01:06:39| 10   1  90   0   0   0|   0    42k|   0  4.80 |   0     0 |  66B  459B|7236M 17.8M 3710M 18.7G
13-09 01:06:44| 10   1  90   0   0   0|   0    29k|   0  2.00 |   0     0 |  73B  469B|7241M 17.8M 3869M 18.6G
13-09 01:06:49| 10   1  90   0   0   0|   0    26k|   0  1.60 |   0     0 |  66B  456B|7249M 17.8M 4030M 18.4G
13-09 01:06:54| 10   1  90   0   0   0|   0    30k|   0  2.00 |   0     0 |  66B  456B|7253M 17.8M 4191M 18.2G
13-09 01:06:59| 10   1  83   7   0   0|6554B  191M|1.60  1532 |   0     0 |  79B  505B|7256M 17.8M 4351M 18.1G
13-09 01:07:04|  7   0  80  12   0   0|6554B  218M|1.60  1750 |   0     0 |  77B  480B|7260M 17.9M 4467M 18.0G
13-09 01:07:09| 10   0  90   0   0   0|   0    14k|   0  1.20 |   0     0 |  66B  459B|7266M 17.9M 4627M 17.8G
13-09 01:07:14| 10   1  90   0   0   0|   0    53k|   0  5.20 |   0     0 |  66B  456B|7269M 17.9M 4788M 17.6G
13-09 01:07:19| 10   1  90   0   0   0|   0    46k|   0  3.20 |   0     0 |  66B  456B|7274M 17.9M 4950M 17.5G
13-09 01:07:24| 10   0  90   0   0   0|   0    19k|   0  1.20 |   0     0 |  66B  456B|7278M 17.9M 5110M 17.3G
13-09 01:07:29|  7   1  92   1   0   0|1638B   47M|0.40   380 |   0     0 |  92B  558B|1373M 17.9M 5223M 23.0G
13-09 01:07:34|  0   0  94   6   0   0|9830B  255M|2.40  2038 |   0     0 |  66B  470B|1373M 18.0M 5223M 23.0G
13-09 01:07:39|  0   0  98   2   0   0|1638B   78M|0.40   628 |   0     0 |  66B  472B|1373M 18.0M 5223M 23.0G
13-09 01:07:44|  0   0 100   0   0   0|   0    22k|   0  1.20 |   0     0 |  66B  457B|1373M 18.0M 5223M 23.0G
13-09 01:07:49|  0   0 100   0   0   0|   0    50k|   0  5.60 |   0     0 |  79B  508B|1373M 18.0M 5223M 23.0G^C


`

**Comment by edenhill** [comment] 2016-09-14 07:34
What's the broker CPU usage when you run this?

**Comment by edenhill** [comment] 2016-09-14 10:29
I found the root cause of this issue:
OpenSSL's per-write overhead SSL_write() is quite high and since librdkafka makes use of iovecs that needs to be fanned out into one SSL_write() call per iovec the resulting throughput for small messages (many iovecs) is quite poor.

The fix for this is to copy small message payloads into contigouous memory when using SSL.
SSL_write does not seem to accept more than about ~64k per write so that is probably a good limit.

**Comment by edenhill** [comment] 2016-09-15 09:07
Can you update to latest master and rerun your benchmarks again?
Please report your findings.

**Comment by pachacutec** [comment] 2016-09-15 15:23
Thanks Sure!!

**Comment by pachacutec** [comment] 2016-09-16 13:17
I running the test I am seeing that is working faster for few record send. But my test that is sending 5M of packages is not finishing. I will submit detail soon.

**Comment by pachacutec** [comment] 2016-09-16 17:01
I've just test, We got 50k that is near of  you 64k. 
The issue was a memory queue queue.buffering.max.kbytes	, 
Thanks

**Comment by edenhill** [comment] 2016-09-16 17:05
What I've seen in my tests that's about what the broker can do with SSL, but don't take my word for it. With more brokers and balanced partitions across them you should be able to multiply that number accordingly.

**Comment by edenhill** [comment] 2016-09-22 16:09
Are you happy with the new numbers?

**Comment by pachacutec** [comment] 2016-09-23 16:59
it's ok, however we are 4x below our measure in PlainText. As soon I got addition values from java producer in ssl, I will let you know.

**Comment by pachacutec** [comment] 2016-09-29 15:44
Thanks you for support. Let me put on this words,
In fact the # are low, but let me ask this question, do you think could done something in librd to improve those #? Although, the fix take time, the point is, SSL is not adding too much overhead in transmission.

**Comment by edenhill** [comment] 2016-09-29 15:51
From what Ive seen the thruput is now capped by the broker SSL performance (it hits full CPU and librdkafka doesnt). Are you seeing the same or does it seem like the broker's could take a higher transmission rate?

**Comment by pachacutec** [comment] 2016-09-30 16:40
It seems the broker could get more load, but I am not sure..
->Metric Broker <--
Linux 3.13.0-92-generic (ip-172-31-4-205)       09/30/2016      _x86_64_        (4 CPU)
04:37:05 PM   UID       PID    %usr %system  %guest    %CPU   CPU  Command
04:37:07 PM  1000      1259    0.50    0.00    0.00    0.50     1  java
04:37:09 PM  1000      1259    0.00    0.50    0.00    0.50     1  java
04:37:11 PM  1000      1259    0.50    0.00    0.00    0.50     1  java
04:37:13 PM  1000      1259    0.00    0.00    0.00    0.00     1  java
04:37:15 PM  1000      1259    0.50    0.00    0.00    0.50     1  java
04:37:17 PM  1000      1259    0.00    0.00    0.00    0.00     1  java
04:37:19 PM  1000      1259    0.50    0.00    0.00    0.50     1  java
04:37:21 PM  1000      1259    0.00    0.00    0.00    0.00     1  java
04:37:23 PM  1000      1259    0.00    0.00    0.00    0.00     1  java
04:37:25 PM  1000      1259    0.50    0.00    0.00    0.50     1  java
04:37:27 PM  1000      1259    0.00    0.00    0.00    0.00     1  java
04:37:29 PM  1000      1259    0.50    0.00    0.00    0.50     1  java
04:37:31 PM  1000      1259    5.00    0.00    0.00    5.00     1  java
04:37:33 PM  1000      1259   34.00    2.50    0.00   36.50     1  java
04:37:35 PM  1000      1259   71.14    4.98    0.00   76.12     1  java
04:37:37 PM  1000      1259   95.00    4.50    0.00   99.50     1  java
04:37:39 PM  1000      1259   80.50    7.00    0.00   87.50     1  java
04:37:41 PM  1000      1259   80.00    4.00    0.00   84.00     1  java
04:37:43 PM  1000      1259   82.00    5.50    0.00   87.50     1  java
04:37:45 PM  1000      1259   81.50    5.00    0.00   86.50     1  java
04:37:47 PM  1000      1259   87.00    4.00    0.00   91.00     1  java
04:37:49 PM  1000      1259   86.50    7.00    0.00   93.50     1  java
04:37:51 PM  1000      1259   78.50    5.00    0.00   83.50     1  java
04:37:53 PM  1000      1259   82.50    6.50    0.00   89.00     1  java
04:37:55 PM  1000      1259   22.50    2.00    0.00   24.50     1  java
04:37:57 PM  1000      1259    0.00    0.00    0.00    0.00     1  java
04:37:59 PM  1000      1259    0.50    0.00    0.00    0.50     1  java
04:38:01 PM  1000      1259    0.00    0.00    0.00    0.00     1  java
-> Metric RD Lib <--
Linux 3.13.0-92-generic (ip-172-31-4-205)       09/30/2016      _x86_64_        (4 CPU)

04:37:28 PM   UID       PID    %usr %system  %guest    %CPU   CPU  Command

04:37:32 PM  1000      2666   59.00   25.50    0.00   84.50     0  rdkafka_perform
04:37:34 PM  1000      2666   70.50   32.00    0.00  102.50     1  rdkafka_perform
04:37:36 PM  1000      2666   37.00   15.00    0.00   52.00     2  rdkafka_perform
04:37:38 PM  1000      2666   40.50   14.00    0.00   54.50     2  rdkafka_perform
04:37:40 PM  1000      2666   42.00   12.00    0.00   54.00     3  rdkafka_perform
04:37:42 PM  1000      2666   44.50   11.00    0.00   55.50     0  rdkafka_perform
04:37:44 PM  1000      2666   41.00   14.00    0.00   55.00     3  rdkafka_perform
04:37:46 PM  1000      2666   42.00   12.00    0.00   54.00     3  rdkafka_perform
04:37:48 PM  1000      2666   46.00   10.50    0.00   56.50     0  rdkafka_perform
04:37:50 PM  1000      2666   47.50    8.00    0.00   55.50     1  rdkafka_perform
04:37:52 PM  1000      2666   45.00   10.50    0.00   55.50     3  rdkafka_perform

**Comment by pachacutec** [comment] 2016-10-13 18:16
Do you know when this fixed will be "officially" release. I mean I require to use a version of librd with this fix since is not "tag" or branch, it is difficult to use just by the commit, Is the 15-Oct the release date for 0.9.2?

**Comment by edenhill** [comment] 2016-10-13 18:17
0.9.2 will most likely be released within 2 weeks.

**Comment by edenhill** [comment] 2016-10-13 18:18
Please give 0.9.2-dev branch (or master) a spin in your setup to assist in final release testing.

**Comment by edenhill** [comment] 2016-10-19 15:39
I will close this issue as it fixed the obvious SSL performance problem.

If you still feel there is more performance to gain I urge you to open a new issue.

Thanks

**Closed by edenhill** 2016-10-19 15:39 UTC
Labels: enhancement

**Comment by pachacutec** [comment] 2016-10-19 17:38
Thanks, Do you have tentative day for the release 0.9.2?

**Comment by edenhill** [comment] 2016-10-19 17:40
within two weeks
