### ISSUE TITLE
unknown partition 

### ISSUE THREAD

**Issue by wangyanshun** [edenhill/librdkafka#887] opened 2016-11-06 15:53 UTC
Description
===========

today， I  got the follow error log .  And I restart my server ,but it is not fixed. 
Would u give me some suggestion ？

KAFKA-4-LEADER: rdkafka#producer-8 Topic XXXX: partition [15] is unknown (partition_cnt 11)

How to reproduce
================

Now， I do not known How to reproduce .

Checklist
=========
Please provide the following information:

 - [v0.8  ] librdkafka version (release number or git tag):
 - [  ] Apache Kafka version: 
 - [  default ] librdkafka client configuration:
 - [ linux ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment] 2016-11-06 19:22
This is fixed on latest master (soon 0.9.2)

**Closed by edenhill** 2016-11-06 19:22 UTC

**Comment by wangyanshun** [comment] 2016-11-06 23:15
Would you  tell me the reasion  and  What should I do to recover my service ？

**Comment by edenhill** [comment] 2016-11-07 06:59
This is typically caused by an out-of-sync broker during a broker failover where the new and old broker's partition count for a topic is different.
librdkafka has improved its handling of this lately and you should try upgrading.

**Comment by wangyanshun** [comment] 2016-11-07 14:57
ok, I will upgrade the librdkafka. Thank you.

**Comment by wangyanshun** [comment] 2016-11-08 06:51
About unknown partition question, Would you give me the commit number to fix the queston. I want to know the reason details and to avoid it . Because we  have a large of server cluster  and now We are  upgrading the kafka server cluster ,in this progress we will change the broker. I am worry about that will be triggered when we are  upgrading.

Thanks for your help.

**Comment by edenhill** [comment] 2016-11-08 08:02
You probably want to investigate why brokers reported errors for half an hour, but that is outside the scope of librdkafka.

There's little a client can do if the brokers are out of sync and one broker reports 11 partitions for a topic while another one reports 16.

**Comment by wangyanshun** [comment] 2016-11-08 08:48
Last question,   Is it a bug of the librdkafka ? Thank you .

**Comment by wangyanshun** [comment] 2016-11-08 08:57
If you like ，I want to be a developer for the librdkafka. My system is processing of large amounts of data, about 20TB every day，it may be a good scene for the librdkafka. @edenhill

**Comment by edenhill** [comment] 2016-11-08 08:59
I wouldnt say it is a bug per say, but it is an interesting discussion how a client should handle certain broker errors/problems.
For example in this case where the partition count for a topic decreases, what should the client do:
 * ignore the changes (but if the topic was re-created with a lower partition count the client will never adjust)
 * adhere to the changes and fail messages for the removed partitions

**Comment by edenhill** [comment] 2016-11-08 08:59
I'd be happy to accept contributions to the project and your use-case sounds intriguing.
If you have areas where you see that the library could be improved I'd be happy to discuss it with you.

**Comment by wangyanshun** [comment] 2016-11-08 09:10
I have to say the librdkafka is a very very very good lib, now I am reading the code and research it. If I have some questions , We will discuss it by git hub or by email ，Which way  is you  like？

**Comment by edenhill** [comment] 2016-11-08 09:16
Thank you, I'm trying to understand it myself! ;)

Use github issues for issues/questions that may be of interesting to other people, for other things email is fine (rdkafka@edenhill.se)

**Comment by wangyanshun** [comment] 2016-11-08 09:28
Thank you, Have a nice day. ;) I will continue my work.;)

**Comment by wangyanshun** [comment] 2016-11-11 07:49
I try my best to reproduce this exception ,like you said, I try to make some broker out-of-sync, but failed. I  can not reproduce, would you give me some more suggestion?
