### ISSUE TITLE
Library assert with "cant handle op type" at time for OAuth Token refresh

### ISSUE THREAD

**Issue by markus8109** [edenhill/librdkafka#3263] opened 2021-02-14 06:57 UTC
Description
===========
We are using the library built with SSL and OAuth support on windows.
The first callback to oauthbearer_token_refresh_cb at startup works fine and the communication start up. The token is valid for one hour, and the token is expected to be refreshed when 80% of the time has lapsed, so at 48 minutes, the library is expected to issue a callback to oauthbearer_token_refresh_cb, but instead it assert and crash the application with the message "cant handle op type"

The attached log is from a unit test where the expiry time is set to 10 minutes and the assert is presented after 8 minutes.

How to reproduce
================
Configuration::set( debug, all )
Configuration::set( metadata.broker.list, <address>:9093 )
Configuration::set( group.id, adbsafegate-consumer-1613283722 )
Configuration::set( statistics.interval.ms, 60000 )
Configuration::set( security.protocol, SASL_SSL )
Configuration::set( sasl.mechanism, OAUTHBEARER )

DefaultTopicConfiguration::set( auto.offset.reset, beginning )
DefaultTopicConfiguration::set( enable.auto.commit, false )

callbacks registered:
rd_kafka_conf_set_log_cb
rd_kafka_conf_set_error_cb
rd_kafka_conf_set_throttle_cb
rd_kafka_conf_set_stats_cb
rd_kafka_conf_set_oauthbearer_token_refresh_cb
rd_kafka_conf_set_ssl_cert_verify_cb
rd_kafka_conf_set_background_event_cb
rd_kafka_conf_set_rebalance_cb
rd_kafka_conf_set_offset_commit_cb

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `v1.5.3`
 - [x] Apache Kafka version: Not available, this must be a client side issue
 - [x] librdkafka client configuration: see in "reproduce"
 - [x] Operating system: `Windows Server 2016`
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
 - [x] Provide broker log excerpts: Not available, this must be a client side issue
 - [x] Critical issue

[ctest.log](https://github.com/edenhill/librdkafka/files/5977105/ctest.log)

**Comment by edenhill** [comment] 2021-02-14 18:22
Is this crash happening in consumer_poll()?
Are there any queues being forward? (queue_forward..())?

**Comment by markus8109** [comment] 2021-02-15 13:51
We're polling for messages in batches using rd_kafka_queue_get_consumer followed by rd_kafka_consume_batch_queue where the crash happens.
We are not using rd_kafka_consumer_poll at all

**Comment by markus8109** [comment] 2021-02-15 16:34
Workaround:
- not setting the consumer to forward events to the message poll queue using rd_kafka_poll_set_consumer
- wrapped the consumer poll and poll_batch functions and are calling poll (for events) before trying to get messages
Now the callbacks for OAuth token refresh are working perfectly.

So the question remains, why are callbacks to the OAuth token refresh not working after the client have been set to use rd_kafka_poll_set_consumer?
The initial OAuth token is set before rd_kafka_poll_set_consumer is being called

**Comment by edenhill** [comment] 2021-02-16 08:33
I think the problem is that consume_batch*() doesn't support all callback types, which is a bug of course.
I'll look into it.

**Comment by lpsinger** [comment] 2022-03-16 16:25
Is there a workaround for this that will work when calling `Consumer.consume()` after `oauth_cb` has been set in confluent-kafka-python?

**Comment by edenhill** [comment] 2022-03-29 10:29
@lpsinger Are you seeing this assert in confluent-kafka-python as well?

**Comment by lpsinger** [comment] 2022-03-29 12:39
> @lpsinger Are you seeing this assert in confluent-kafka-python as well?

Yes. Clarification: I am using confluent-kafka-python, and I am _not_ using librdkafka directly.

**Comment by edenhill** [comment] 2022-03-29 19:03
Fixed on master, will be included in upcoming 1.9.0 release.

**Closed by edenhill** 2022-03-29 19:03 UTC
