### ISSUE TITLE
librdkafka not handling broker-based offsets correctly

### ISSUE THREAD

**Issue by jcalcote** [edenhill/librdkafka#1599] opened 2017-12-19 03:48 UTC
Description
===========
Hi Magnus, I've got a small library that uses conditional compilation to enable or disable broker-based offsets in librdkafka. When I have broker-based offsets disabled, I use a (non-optimal) seek algorithm to start at the beginning and process all of the messages on the topic until I find the one I want. I'd rather just use broker-base stored offsets so I can simply update the stored value to the one I know is correct during the run of the program. When the program next starts up, I could just tell the consumer to start at the last stored offset.

Now, I'll state right off that we're using this kafka topic as a sort of RPC mechanism where the client sends a request message and the server responds on the same topic with a response message. 

When broker-based stored offsets are enabled, after sending my first request, the responder responds by sending the response and that response is apparently lost because my "client" consumer never gets it. This seems to happen more often than not when the bus (and topic) are empty. Is there any reason you can think of why an empty topic would have trouble receiving the second message? (The first was the request message.)

I'm also indicating via auto.offset.reset that I wish to reset to the largest offset on missing offset. Could it be possible that I'm actually losing the first message due to this setting? I've executed the "client" in gdb and watched the messages coming through - I don't even get the first request message - I just get three copies of an error - "Broker: No more messages" in all three calls to my callback. This feels like there are three messages - the first two should be my request and response, the last should be the regular EOP message.

Thoughts?

**Comment by edenhill** [comment] 2018-01-03 15:08
> I'm also indicating via auto.offset.reset that I wish to reset to the largest offset on missing offset. > Could it be possible that I'm actually losing the first message due to this setting?

Yes, this is most likely the cause.
If your consumer starts consuming after the messages have been produced, and it does not have a valid committed offset to start at, it will resort to auto.offset.reset which defaults to latest, or more specifically, the end of the partition. This means it will only see new messages produced after the consumer has been started.
The "Broker: No more messages" error is not really an error but an informational event letting you know the fetcher has reached the end of a partition, this is needed by some applications (e.g., read to the end and then do something else) but you can disable these events if you don't need them by setting `enable.partition.eof` to "false", or simply ignoring these error codes.

So, my suggestion is to use auto.offset.reset=earliest to properly catch up when there is no valid committed offset to start with, or alternatively, make sure the consumer is fully started before the producer sends messages (which is harder to synchronize).

**Comment by jcalcote** [comment] 2018-01-04 18:24
Thanks - you can close this ticket - using "auto.offset.reset=earliest" appears to have solved my lost request issue.

**Closed** 2018-01-04 18:26 UTC
