### ISSUE TITLE
kafka 0.10.0.1 with librdkafka 0.9.1 or 0.9.2 or trunk compatibility

### ISSUE THREAD

**Issue by HQebupt** [edenhill/librdkafka#907] opened 2016-11-15 10:17 UTC
Description
===========
### environment
- rsyslog v8.11
- librdkafka 0.9.1 or 0.9.2 or trunk
- kafka broker version: 0.10.0.1
- OS: Linux

I update librdkafka version to 0.9.1 or higher, for supporting kafka 0.10.0.1. And I got the exception from the broker log. It happens accidentally.(several hours period)
```
java.io.IOException: org.apache.kafka.common.errors.UnsupportedSaslMechanismException: Exception handling first SASL packet from client, GSSAPI is not supported by server
        at org.apache.kafka.common.security.authenticator.SaslServerAuthenticator.authenticate(SaslServerAuthenticator.java:243)
        at org.apache.kafka.common.network.KafkaChannel.prepare(KafkaChannel.java:64)
        at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:318)
        at org.apache.kafka.common.network.Selector.poll(Selector.java:283)
        at kafka.network.Processor.poll(SocketServer.scala:472)
        at kafka.network.Processor.run(SocketServer.scala:412)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.kafka.common.errors.UnsupportedSaslMechanismException: Exception handling first SASL packet from client, GSSAPI is not supported by server
Caused by: org.apache.kafka.common.protocol.types.SchemaException: Error reading field 'client_id': Error reading string of length 27759, only 70 bytes available
        at org.apache.kafka.common.protocol.types.Schema.read(Schema.java:73)
        at org.apache.kafka.common.requests.RequestHeader.parse(RequestHeader.java:80)
        at org.apache.kafka.common.security.authenticator.SaslServerAuthenticator.handleKafkaRequest(SaslServerAuthenticator.java:295)
        at org.apache.kafka.common.security.authenticator.SaslServerAuthenticator.authenticate(SaslServerAuthenticator.java:223)
        at org.apache.kafka.common.network.KafkaChannel.prepare(KafkaChannel.java:64)
        at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:318)
        at org.apache.kafka.common.network.Selector.poll(Selector.java:283)
        at kafka.network.Processor.poll(SocketServer.scala:472)
        at kafka.network.Processor.run(SocketServer.scala:412)
        at java.lang.Thread.run(Thread.java:745)
[2016-11-15 13:25:22,566] DEBUG Received client packet of length 80 starting with bytes 0x6d617069527379736c6f, process as GSSAPI packet (org.apache.kafka.common.security.authenticator.SaslServerAuthenticator)
[2016-11-15 13:25:22,566] DEBUG Set SASL server state to FAILED (org.apache.kafka.common.security.authenticator.SaslServerAuthenticator)
```

my configuration
====
```
action (
         type="omkafka"
         broker=["..."]
         confParam=["sasl.mechanisms=PLAIN","security.protocol=sasl_plaintext","sasl.username=xxx","sasl.password=xxx","api.version.request=true"]
         topic="xxx"
         template="processlogLogFormat"
         partitions.auto="on"
         name="action_xxxx"
         queue.type="linkedlist"
         queue.size="100000"
         queue.dequeuebatchsize="5000"
   )

```
Is there any problem ? or just bug?

Thanks.

**Comment by edenhill** [comment] 2016-11-15 10:33
So this only happens occassionally?
Do you have any network problems such that a given client->broker request would take more than 10s at certain times?
The reason I'm asking is that brokers 0.9.0.0 had a bug where it would simply ignore unknown requests, such as ApiVersionRequest (which was added in 0.10.0.0), librdkafka can't know the broker version so it handles this by having a hard-fixed timeout of 10s on ApiVersionRequests.
If the broker or network is congested, slow, for any reason and the request takes that long then librdkafka will fall back to broker.version.fallback.
And if broker.version.fallback is set < 0.10 it will attempt to SASL PLAIN authenticate using a framing that brokers think is GSSAPI / Kerberos, and not PLAIN.

This should be fixed in librdkafka.

**Comment by HQebupt** [comment] 2016-11-16 03:21
Thanks for your reply. It only happens occassionally during a day, such as 2016-11-14T00,2016-11-14T06,2016-11-14T14.  (every time lasts about 10 minutes.) 
In **my configuration** above,`"api.version.request=true"`, and I do not set ` broker.version.fallback`.
What caused this error, do you have any idea ? 
```
Caused by: org.apache.kafka.common.protocol.types.SchemaException: Error reading field 'client_id': Error reading string of length 27759, only 70 bytes available
```

Here is kafka 0.10.0.1 `config/server.properties`.
```
############################ Socket Server Settings #############################
listeners=SASL_PLAINTEXT://localhost:9110
security.inter.broker.protocol=SASL_PLAINTEXT
sasl.mechanism.inter.broker.protocol=PLAIN
sasl.enabled.mechanisms=PLAIN
````

**Comment by edenhill** [comment] 2016-11-21 11:26
Can you reproduce this with `debug=protocol,security,broker`?

**Closed** 2017-01-03 12:31 UTC
Labels: wait-info
