### ISSUE TITLE
Producer sending data to non replica leader

### ISSUE THREAD

**Issue by saheemg** [edenhill/librdkafka#1665] opened 2018-02-01 15:07 UTC
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
Kafka broker errors: broker 2:org.apache.kafka.common.errors.NotLeaderForPartitionException: This server is not the leader for that topic-partition
when publishing using 0.9.5 verison of librdkafka

Broker Logs:

[2018-02-01 07:57:02,338] ERROR [ReplicaFetcher replicaId=8, leaderId=2, fetcherId=0] Error for partition events-82 to broker 2:org.apache.kafka.common.errors.NotLeaderForPartitionException: This server is not the leader for that topic-partition. (kafka.server.ReplicaFetcherThread)
[2018-02-01 07:57:02,338] ERROR [ReplicaFetcher replicaId=8, leaderId=3, fetcherId=0] Error for partition metrictank-1692 to broker 3:org.apache.kafka.common.errors.NotLeaderForPartitionException: This server is not the leader for that topic-partition. (kafka.server.ReplicaFetcherThread)
[2018-02-01 07:57:02,338] ERROR [ReplicaFetcher replicaId=8, leaderId=14, fetcherId=0] Error for partition metrictank_persist-1453 to broker 14:org.apache.kafka.common.errors.NotLeaderForPartitionException: This server is not the leader for that topic-partition. (kafka.server.ReplicaFetcherThread)
[2018-02-01 07:57:02,337] ERROR [ReplicaFetcher replicaId=11, leaderId=1, fetcherId=0] Error for partition metrictank-822 to broker 1:org.apache.kafka.common.errors.NotLeaderForPartitionException: This server is not the leader for that topic-partition. (kafka.server.ReplicaFetcherThread)
[2018-02-01 07:57:02,337] ERROR [ReplicaFetcher replicaId=15, leaderId=5, fetcherId=0] Error for partition metrictank-1857 to broker 5:org.apache.kafka.common.errors.NotLeaderForPartitionException: This server is not the leader for that topic-partition. (kafka.server.ReplicaFetcherThread)
 

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `0.9.5`
 - [x ] Apache Kafka version: `1.0.0`
 - [x] librdkafka client configuration: `compression.codec=snappy, delivery.report.only.error=true`
 - [x ] Operating system: `rhel 7`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [x ] Provide broker log excerpts
 - [x ] Critical issue

**Comment by edenhill** [comment] 2018-02-01 15:42
Does this happen when the current leader fails, or spontaneously without broker leader change?

**Comment by saheemg** [comment] 2018-02-01 17:12
Can't say for sure.  I do see in the broker logs around the time I see the leader error log:

`WARN [ReplicaFetcher replicaId=8, leaderId=11, fetcherId=0] Based on follower's leader epoch, leader replied with an unknown offset in ... High watermark 229171041 will be used for truncation. (kafka.server.ReplicaFetcherThread)`

**Comment by edenhill** [comment] 2018-02-01 17:23
So it looks like there might have been a leader change.

Does the producer eventually sort itself out or does it continue producing to the wrong broker forever?
I'm quite certain the latter has been fixed in 0.11.3 or possibly the upcoming 0.11.4 release (which has plenty of good producer retry fixes)

**Comment by saheemg** [comment] 2018-02-01 17:51
We actually have to bounce the producer.

ETA for 0.11.4?

**Comment by edenhill** [comment] 2018-02-01 17:53
Mid-late february

**Comment by saheemg** [comment] 2018-02-01 18:09
BTW, the producer is getting a rc = -184  from `RdKafka::Produce::produce` method call

**Comment by edenhill** [comment] 2018-02-01 18:12
That's ERR__QUEUE_FULL which will be returned from produce() when the internal producer queue is full, which is caused by the producer not being able to deliver messages at all or in due time.

**Comment by saheemg** [comment] 2018-02-01 18:14
So is this is a side effect of it not sending the message to the proper leader?

**Comment by edenhill** [comment] 2018-02-01 18:21
Yep

**Closed** 2018-02-05 14:46 UTC
Labels: bug

**Comment by alexvs11** [comment] 2018-04-08 17:47
Hi @edenhill, 

Any chance you can recall which commit has fixed this issue?
I only can say that It is 100% reproducible (after graceful restart of a broker) with 0.9.5 rdkafka and definitely has gone away in 0.11.3.

Thanks in advance.

**Comment by edenhill** [comment] 2018-04-09 05:45
Sorry no, check for hints in release notes: https://github.com/edenhill/librdkafka/releases
