### ISSUE TITLE
Way to get correct offset for each message published on consumer side.

### ISSUE THREAD

**Issue by rathdeep** [edenhill/librdkafka#335] opened 2015-07-17 15:45 UTC
I have seen other threads regarding offset, but unable to find a correct answer.

I am getting current end of queue offset by
./rdkafka_example -C -b broker -t topic  -p 0.  Let’s say 30

On producer side, I am sending around 20000 messages. And in msg_delivered2, I am printing offset as shown in rdkafka_example.c.
And I noticed, I get same offset repeated for many messages and minimum value > 30. Also maximum offset received on consumer side >30 + 20000.

whereas ./rdkafka_example -C -b broker -t topic  -p 0.  Says current end of queue offset is 30+ 20000

Consumer side code is also similar to rdkafka_example.c

While
{
                if (rd_kafka_produce(rkDataTopic, dataPartition,
                                     
               
/* Poll to handle delivery reports */
                rd_kafka_poll(rk, 0);
}
>>>>>>>>>>>>>>>>>>>>>>>>>>>

Now, if I add delay between two produce, I get better results. Although it starts from 30 +1  

Like 
While
{
                if (rd_kafka_produce(rkDataTopic, dataPartition,
                                     
               /* Poll to handle delivery reports */
                sleep(1);
                rd_kafka_poll(rk, 0);
}

Is this expected behavior. Basically, I want to retrieve the offset of first produced message from producer side which consumers can use.

**Comment by edenhill** [comment] 2015-07-17 22:55
First you need to configure `produce.offset.report=true` on your rd_kafka_topic_conf_t object to get correct offsets for produced messages.

Secondly, librdkafka is fully asynchronous, so when you call produce() all it does is enqueue your message on an internal queue for tranmission to the broker, thus if you do produce() quickly followed by poll() you will most likely NOT get the delivery report callback for the message you just sent but more likely for a previous message.

**Comment by rathdeep** [comment] 2015-07-19 15:12
I have set produce.offset.report=true using rd_kafka_topic_conf_set method.
I do get delivery report callback using poll, but the offset number reported is wrong if i don't place a sleep(1) as shown in above example. I publish 20000 msgs one after another.

Placing sleep(1) between produce and poll gives the first offset as one more than actual one. Have explained this above in my previous comment. According to you it shouldn't behave this way??

Also, is it guaranteed that message delivery callbacks will be called in the same order matching the order in which messages were published. it seems so as offset were always increasing.

Thanks,

**Comment by rathdeep** [comment] 2015-07-19 17:59
same behavior can be reproduced when using rdkafka_performance to produce msgs (lets say 200) and using rdkafka_example to consume messages.Offsets on producer and consumer do not match.


With 1 message produced:
----------------------------------
Producer ( offset is one more than consumer):
% All messages produced, now waiting for 1 deliveries
% Message delivered (offset 148140192): 0 remain
All messages delivered!
% 0 messages in outq
% 1 messages produced (1600 bytes), 1 delivered (offset 148140192, 0 failed) in 158ms: 6 msgs/s and 0.01 Mb/s, 0 produce failures, 0 in queue, no compression


Consumer:
% Consumer reached end of TOPIC1 [0] message queue at offset 148140192

With 200 msgs ( producer offset is much more than consumer)
------------------------------------------------------
Producer:
% Message delivered (offset 148140591): 2 remain
% Message delivered (offset 148140592): 1 remain
% Message delivered (offset 148140593): 0 remain
All messages delivered!
% 0 messages in outq
% 200 messages produced (320000 bytes), 200 delivered (offset 148140593, 0 failed) in 164ms: 1217 msgs/s and 1.95 Mb/s, 0 produce failures, 0 in queue, no compression

Consumer
% Consumer reached end of TOPIC1 [0] message queue at offset 148140394

**Comment by edenhill** [comment] 2015-07-19 18:01
Are you running the producer and consumer simultaneously, or one after the other? If so, how much delay do you have between producer and consumer start and stop?
Could you please provide a detailed timeline on how and when you execute the different commands?
Thanks

**Comment by rathdeep** [comment] 2015-07-20 06:53
Here you go… I have not made any change to the example code.

1> On one Linux terminal (Consumer)
--------------------------------------
./rdkafka_example -C -b broker.IP  -t TOPIC1 -p 0 
% Consumer reached end of TOPIC1  [0] message queue at offset 148160395

2> Then on second terminal (Producer)
---------------------
./rdkafka_performance -P -b broker.IP  -t TOPIC1 -s 20 -c 1 -a -1 -p 0 -m "ddddddddddddddddddddddddfff" -O -v -e
% Using random seed 1437374727, verbosity level 2
% Sending 1 messages of size 20 bytes
% 1 messages produced (20 bytes), 0 delivered (offset 0, 0 failed) in 0ms: 0 msgs/s and 0.00 Mb/s, 0 produce failures, 1 in queue, no compression
% All messages produced, now waiting for 1 deliveries
% Message delivered (offset 148160396): 0 remain
All messages delivered!
% 0 messages in outq
% 1 messages produced (20 bytes), 1 delivered (offset 148160396, 0 failed) in 114ms: 8 msgs/s and 0.00 Mb/s, 0 produce failures, 0 in queue, no compression


3> On Consumer terminal one, got following message:
% Message (offset 148160395, 20 bytes):
148160395 OFFSET OF MESSAGE
Message Payload hexdump (20 bytes):
00000000: 64 64 64 64 64 64 64 64 64 64 64 64 64 64 64 64  dddddddddddddddd
00000010: 64 64 64 64                                      dddd
% Consumer reached end of TOPIC1 [0] message queue at offset 148160396

Producer shows offset is 148160396. Consumer shows 148160395.
===========================

**Comment by edenhill** [comment] 2015-07-20 07:08
Thanks for your detailed information.
I can't reproduce this, I get the proper offsets:

Producer produces msg offset 197
============================
`````
$ examples/rdkafka_performance -P -b eden -t test -p 0 -s 20 -a -1 -c 1 -O -v  -m "msg e"
% Using random seed 1437375984, verbosity level 2
% Sending 1 messages of size 20 bytes
% 1 messages produced (20 bytes), 0 delivered (offset 0, 0 failed) in 0ms: 0 msgs/s and 0.00 Mb/s, 0 produce failures, 1 in queue, no compression
% All messages produced, now waiting for 1 deliveries
% Message delivered (offset 197): 0 remain
All messages delivered!
% 0 messages in outq
% 1 messages produced (20 bytes), 1 delivered (offset 197, 0 failed) in 16ms: 59 msgs/s and 0.00 Mb/s, 0 produce failures, 0 in queue, no compression

`````

Consumer sees offsets 197
======================
`````
% Consumer reached end of test [0] message queue at offset 197
% Message (offset 197, 20 bytes):
Message Payload hexdump (20 bytes):
00000000: 6d 73 67 20 65 6d 73 67 20 65 6d 73 67 20 65 6d  msg emsg emsg em
00000010: 73 67 20 65                                      sg e            
% Consumer reached end of test [0] message queue at offset 198
`````

**Comment by rathdeep** [comment] 2015-07-20 07:12
Can you please try for 200 messages too..
1> On one Linux terminal (Consumer)
./rdkafka_example -C -b broker.IP  -t TOPIC1 -p 0 

2> Then on second terminal (Producer)
./rdkafka_performance -P -b broker.IP  -t TOPIC1 -s 20 -c 200 -a -1 -p 0 -m "ddddddddddddddddddddddddfff" -O -v -e

Here i get offset way off between producer and consumer.

**Comment by edenhill** [comment] 2015-07-20 07:14
Works:
**Producer**
````
...
% Message delivered (offset 596): 1 remain
% Message delivered (offset 597): 0 remain
All messages delivered!
````

**Consumer**
````
% Message (offset 596, 20 bytes):
Message Payload hexdump (20 bytes):
00000000: 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41  AAAAAAAAAAAAAAAA
00000010: 41 41 41 41                                      AAAA            
% Message (offset 597, 20 bytes):
Message Payload hexdump (20 bytes):
00000000: 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41  AAAAAAAAAAAAAAAA
00000010: 41 41 41 41                                      AAAA            
% Consumer reached end of test [0] message queue at offset 598
````

**Comment by rathdeep** [comment] 2015-07-20 07:16
Hmm my results:

% Consumer reached end of TOPIC1 [0] message queue at offset 148160596

Then after publishing 200 msgs.

For first message, Producer shows offset is 148160796 and Consumer shows 148160596
For last message, Producer shows offset is 148160995 and Consumer shows 148160795

**Comment by edenhill** [comment] 2015-07-20 07:16
Could you paste the last two messages from the producer and consumer?

**Comment by rathdeep** [comment] 2015-07-20 07:21
This output is for 100 messages:

Producer:
% Message delivered (offset 148160993): 2 remain
% Message delivered (offset 148160994): 1 remain
% Message delivered (offset 148160995): 0 remain
All messages delivered!
% 0 messages in outq
% 100 messages produced (2000 bytes), 100 delivered (offset 148160995, 0 failed) in 129ms: 772 msgs/s and 0.02 Mb/s, 0 produce failures, 0 in queue, no compression


Consumer:
% Message (offset 148160894, 20 bytes):
148160894 OFFSET OF MESSAGE
Message Payload hexdump (20 bytes):
00000000: 64 64 64 64 64 64 64 64 64 64 64 64 64 64 64 64  dddddddddddddddd
00000010: 64 64 64 64                                      dddd
% Message (offset 148160895, 20 bytes):
148160895 OFFSET OF MESSAGE
Message Payload hexdump (20 bytes):
00000000: 64 64 64 64 64 64 64 64 64 64 64 64 64 64 64 64  dddddddddddddddd
00000010: 64 64 64 64                                      dddd
% Consumer reached end of TOPIC1  [0] message queue at offset 148160896

**Comment by edenhill** [comment] 2015-07-20 07:29
Are you stopping the consumer after that or do you let it run?
The messages should arrive eventually.

**Comment by edenhill** [comment] 2015-07-20 07:29
Can we continue on gitter? https://gitter.im/edenhill/librdkafka

**Comment by rathdeep** [comment] 2015-07-20 07:38
No, i am not stopping consumer.. It got all 100 messages produced using rdkafka_performance . 

Are you aware of any Kafka broker side settings for this to work.

Sorry, can't access gitter this time.

**Comment by rathdeep** [comment] 2015-07-20 08:17
Basically the reason i need correct offset is, i am going publish that info in some topic. Clients will read that topic and subscribes data from correct offset onward.

**Comment by edenhill** [comment] 2015-07-20 08:19
Are you using latest master?

**Comment by rathdeep** [comment] 2015-07-20 08:20
yes.. i downloaded few weeks ago.

librdkafka version 0.8.6 (0x00080600)

**Comment by edenhill** [comment] 2015-07-20 08:20
This all sounds very weird, there might be a short delay between produce and consume but it should be in the 100ms range, not more.

Can you try passing the `-S 1000`  option to kafka_performance? That makes it prepend a sequence number (starting at 1000) in each message. That way we can check if produced message #200 actually contains "1200..", and we can see what the offset is for each message.

**Comment by rathdeep** [comment] 2015-07-20 08:38
i tried removing "request.required.acks" argument (-a) and it works fine.

passing  -a -1 to kafka_performance (producer)  which will add some latency, makes offset to be reported wrongly.

**Comment by rathdeep** [comment] 2015-07-20 08:49
With -S option, i do see 1199 in 200th message. That's working fine.

Message Payload hexdump (22 bytes):
00000000: 31 31 39 39 3a 20 00 64 64 64 64 64 64 64 64 64  1199: .ddddddddd
00000010: 64 64 64 64 64 64                                dddddd

**Comment by edenhill** [comment] 2015-07-20 10:03
Okay, so with -S you verify that you are actually getting the correct message, but the consumed offset is still wrong?
Some questions:
 * How far off is the offset? Is that number consistent?
 * What does your topic look like, please provide output of `rdkafka_example .. -L -t yourtopic`

**Comment by rathdeep** [comment] 2015-07-20 10:27
Yes, all messages are correctly received.

If I produce 20 msgs, producer offset of 20th msg  is 20 more than consumer. Seems to be consistent for 20  msgs. But this number changes if I increase the number of messages produced.
For 200 msgs, it is 200
For 556 mgs, it is 56
For 999 msgs, it is 243

Output for 20 msgs:
Consumer:
% Message (offset 148222936, 22 bytes):
148222936 OFFSET OF MESSAGE
Message Payload hexdump (22 bytes):
00000000: 31 30 31 39 3a 20 00 64 64 64 64 64 64 64 64 64  1019: .ddddddddd
00000010: 64 64 64 64 64 64                                dddddd
% Consumer reached end of TOPIC1[0] message queue at offset 148222937


Producer:
% Using random seed 1437386717, verbosity level 2
% Sending 20 messages of size 22 bytes
% 1 messages produced (22 bytes), 0 delivered (offset 0, 0 failed) in 0ms: 0 msgs/s and 0.00 Mb/s, 0 produce failures, 1 in queue, no compression
% All messages produced, now waiting for 20 deliveries
% Message delivered (offset 148222937): 19 remain
% Message delivered (offset 148222946): 10 remain
% Message delivered (offset 148222952): 4 remain
% Message delivered (offset 148222953): 3 remain
% Message delivered (offset 148222954): 2 remain
% Message delivered (offset 148222955): 1 remain
% Message delivered (offset 148222956): 0 remain
All messages delivered!
% 0 messages in outq
% 20 messages produced (440 bytes), 20 delivered (offset 148222956, 0 failed) in 247ms: 80 msgs/s and 0.00 Mb/s, 0 produce failures, 0 in queue, no compression


Metadata:

3 brokers:
  broker 2340534594  at host1
  broker 2343789123  at host2
  broker 2670552545 at host3
 1 topics:
  topic "TOPIC1" with 2 partitions:
    partition 0, leader 2340534594 , replicas: 2340534594 ,2343789123 , isrs: 2343789123 ,2340534594 
    partition 1, leader 2343789123 , replicas: 2343789123 ,2670552545, isrs: 2670552545,2343789123

**Comment by edenhill** [comment] 2015-07-20 11:24
Interesting.
And this only happens when request.required.acks = -1  (-a)  ?

**Comment by edenhill** [comment] 2015-07-20 11:24
What broker version is this?

**Comment by rathdeep** [comment] 2015-07-20 14:12
yes... issue with a = -1. Does it work for you.. 
broker version is 0.8.0.

**Comment by edenhill** [comment] 2015-07-20 19:35
I think you are hitting this broker bug:
https://issues.apache.org/jira/browse/KAFKA-1255

This is fixed in trunk and will be available in the next broker version (0.8.3)

**Comment by rathdeep** [comment] 2015-07-21 07:37
Thanks. Is it possible to change the conf property after creating the topic. May be I can change “request.required.acks" to -1 after receiving correct offset for first message.

rd_kafka_topic_t *rd_kafka_topic_new (rd_kafka_t *rk, const char *topic,
                                      rd_kafka_topic_conf_t *conf)

**Comment by edenhill** [comment] 2015-07-21 18:59
Configuration can't be changed after the .._new() call though, so that wont work.
Another alternative would be to produce a single message, wait for it to be delivered (and thus get a proper offset since it is only one message, if I understand the bug correctly), then produce as usual.

**Comment by rathdeep** [comment] 2015-07-22 07:41
Even with single message (a=-1), we get wrong offset ( one more than actual). So, basically we need to produce single message with (a!=-1), then recreate that topic with (a=-1) and produce remaining.

**Comment by edenhill** [comment] 2015-07-23 19:31
Alternative you could create a topic with request.required.acks=1, send a message to get offset, destroy the topic, wait some arbitrary time for the topic to decommission inside librdkafka, then create the topic again with request.required.acks=-1 and produce as usual.

**Closed** 2015-08-06 06:42 UTC
Labels: core issue
