### ISSUE TITLE
commitSync() return "No offset stored" after resetting partition to beginning

### ISSUE THREAD

**Issue by hougedengwo** [edenhill/librdkafka#1407] opened 2017-09-04 04:40 UTC
Description
===========
I try to scan partition from beginning to end.
At first I create a consumer, set properties:
group.id as the same topic
auto.offset.reset=smallest
offset.store.method=none
also set "rebalance_cb"

then consuming messages like this:

```
while (run) {
    if (need reset to beginning) {
        std::vector<RdKafka::TopicPartition*> partitions;
        partitions.push_back(RdKafka::TopicPartition::create(_topic
            , _partitionId, RdKafka::Topic::OFFSET_BEGINNING));
        _consumer->assign(partitions);
    }

    RdKafka::Message *msg = _consumer->consume(500);
    switch (msg->err()) {
    case RdKafka::ERR__PARTITION_EOF:
        return RdKafka::ERR__PARTITION_EOF;
    case RdKafka::ERR_NO_ERROR:
        ...
        break;
    ...
    }
    if (consumed messages >= commit batch) {
        RdKafka::ErrorCode err = _consumer->commitSync();
        if (err != RdKafka::ERR_NO_ERROR) {
            std::cerr << "sync commit returned err:"
                << RdKafka::err2str(err) << std::endl;
        }
    }
}

```

It's all right in first scan, but commitSync() return "No offset stored" after resetting partition to beginning.
error log:Local: No offset stored

How to reproduce
================
see above.

Checklist
=========
Please provide the following information:

 - [X] librdkafka version (release number or git tag):0.9.5 0.11.0
 - [X] Apache Kafka version: kafka_2.11-0.10.1.1
 - [X] librdkafka client configuration:see above
 - [X] Operating system:SUSE Linux Enterprise Server 11 (x86_64)
 - [X] Using the legacy Consumer:No
 - [X] Using the high-level KafkaConsumer:Yes
 - [X] Provide logs (with `debug=..` as necessary) from librdkafka
 - [X] Provide broker log excerpts
 - [X] Critical issue

**Comment by edenhill** [comment] 2017-09-04 05:46
I think the problem is that you are trying to commit but you have disabled the offset commit storage engine by setting `offset.store.method=none`.
Remove that config (reverts it to default `broker`) and try again.

**Comment by hougedengwo** [comment] 2017-09-04 13:56
I set offset.store.method=broker, as the default.
In the callback function "void rebalance_cb()":
    if (err == RdKafka::ERR__ASSIGN_PARTITIONS) {
        call set_offset(RdKafka::Topic::OFFSET_BEGINNING) for every item in partitions;
        consumer->assign(partitions);
    }
but the partition can not be consumed from the beginning.

**Comment by edenhill** [comment] 2017-09-04 14:16
Okay, can you reproduce this with `debug=cgrp,topic,fetch` and annotate the log with information where you are calling assign() again, etc?

**Comment by hougedengwo** [comment] 2017-09-05 08:23
Someone set log.retention.minutes=1 of kafka, the partition's log was deleted after one minute. So I got the partition EOF.
After fixing the config of kafka, reset to beginning is OK.  I am sorry for the wrong information.

The problem of "No offset stored" is still there, even setting offset.store.method=broker.
topic "sess5lichun" is created with "--replication-factor 3 --partitions 2"

while (run) {
    if (need reset to beginning) {
        std::vector<RdKafka::TopicPartition*> partitions;
        partitions.push_back(RdKafka::TopicPartition::create(_topic
            , _partitionId, RdKafka::Topic::OFFSET_BEGINNING));
        _consumer->assign(partitions);
    }
Reproduce with debug=cgrp,topic,fetch
The log after the code"_consumer->assign(partitions);" like this:
%7|1504599213.831|CGRPOP|rdkafka#consumer-1| [thrd:main]: Group "sess5lichun" received op ASSIGN (v0) in state up (join state started, v4 vs 0)
%7|1504599213.831|ASSIGN|rdkafka#consumer-1| [thrd:main]: Group "sess5lichun": new assignment of 2 partition(s) in join state started
%7|1504599213.831|DESP|rdkafka#consumer-1| [thrd:main]: Setting topic sess5lichun [0] partition as desired
%7|1504599213.831|DESP|rdkafka#consumer-1| [thrd:main]: Setting topic sess5lichun [1] partition as desired
%7|1504599213.831|BARRIER|rdkafka#consumer-1| [thrd:main]: Group "sess5lichun": rd_kafka_cgrp_assign:2236: new version barrier v5
%7|1504599213.831|CGRPJOINSTATE|rdkafka#consumer-1| [thrd:main]: Group "sess5lichun" changed join state started -> wait-unassign (v5, state up)
%7|1504599213.831|BARRIER|rdkafka#consumer-1| [thrd:main]: Group "sess5lichun": rd_kafka_cgrp_unassign:2152: new version barrier v6
%7|1504599213.831|UNASSIGN|rdkafka#consumer-1| [thrd:main]: Group "sess5lichun": unassigning 2 partition(s) (v6)
%7|1504599213.831|BARRIER|rdkafka#consumer-1| [thrd:main]: sess5lichun [0]: rd_kafka_toppar_op_fetch_stop:2081: new version barrier v3
%7|1504599213.831|CONSUMER|rdkafka#consumer-1| [thrd:main]: Stop consuming sess5lichun [0] (v3)
%7|1504599213.831|DESP|rdkafka#consumer-1| [thrd:main]: Removing (un)desired topic sess5lichun [0]
%7|1504599213.831|BARRIER|rdkafka#consumer-1| [thrd:main]: sess5lichun [1]: rd_kafka_toppar_op_fetch_stop:2081: new version barrier v3
%7|1504599213.831|CONSUMER|rdkafka#consumer-1| [thrd:main]: Stop consuming sess5lichun [1] (v3)
%7|1504599213.831|DESP|rdkafka#consumer-1| [thrd:main]: Removing (un)desired topic sess5lichun [1]
%7|1504599213.831|RESUME|rdkafka#consumer-1| [thrd:main]: Library resuming 2 partition(s)
%7|1504599213.831|BARRIER|rdkafka#consumer-1| [thrd:main]: sess5lichun [0]: rd_kafka_toppar_op_pause_resume:2139: new version barrier v4
%7|1504599213.831|RESUME|rdkafka#consumer-1| [thrd:main]: Resume sess5lichun [0] (v4)
%7|1504599213.831|BARRIER|rdkafka#consumer-1| [thrd:main]: sess5lichun [1]: rd_kafka_toppar_op_pause_resume:2139: new version barrier v4
%7|1504599213.831|RESUME|rdkafka#consumer-1| [thrd:main]: Resume sess5lichun [1] (v4)
%7|1504599213.831|UNASSIGN|rdkafka#consumer-1| [thrd:main]: Unassign not done yet (2 wait_unassign, 2 assigned, 0 wait commit): unassign
%7|1504599213.831|ASSIGN|rdkafka#consumer-1| [thrd:main]: Group "sess5lichun": assigning 2 partition(s) in join state wait-unassign
%7|1504599213.831|DESIRED|rdkafka#consumer-1| [thrd:main]: sess5lichun [0]: adding to DESIRED list
%7|1504599213.831|DESIRED|rdkafka#consumer-1| [thrd:main]: sess5lichun [1]: adding to DESIRED list
%7|1504599213.831|OP|rdkafka#consumer-1| [thrd:main]: sess5lichun [0] received op FETCH_STOP (v3) in fetch-state active (opv2)
%7|1504599213.831|FETCH|rdkafka#consumer-1| [thrd:main]: Stopping fetch for sess5lichun [0] in state active (v3)
%7|1504599213.831|PARTSTATE|rdkafka#consumer-1| [thrd:main]: Partition sess5lichun [0] changed fetch state active -> stopping
%7|1504599213.831|STORETERM|rdkafka#consumer-1| [thrd:main]: sess5lichun [0]: offset store terminating
%7|1504599213.831|PARTSTATE|rdkafka#consumer-1| [thrd:main]: Partition sess5lichun [0] changed fetch state stopping -> stopped
%7|1504599213.831|OP|rdkafka#consumer-1| [thrd:main]: sess5lichun [1] received op FETCH_STOP (v3) in fetch-state active (opv2)
%7|1504599213.831|FETCH|rdkafka#consumer-1| [thrd:main]: Stopping fetch for sess5lichun [1] in state active (v3)
%7|1504599213.831|PARTSTATE|rdkafka#consumer-1| [thrd:main]: Partition sess5lichun [1] changed fetch state active -> stopping
%7|1504599213.831|STORETERM|rdkafka#consumer-1| [thrd:main]: sess5lichun [1]: offset store terminating
%7|1504599213.831|PARTSTATE|rdkafka#consumer-1| [thrd:main]: Partition sess5lichun [1] changed fetch state stopping -> stopped
%7|1504599213.831|OP|rdkafka#consumer-1| [thrd:main]: sess5lichun [0] received op PAUSE (v4) in fetch-state stopped (opv3)
%7|1504599213.831|RESUME|rdkafka#consumer-1| [thrd:main]: Not resuming stopped sess5lichun [0]: at offset 0 (state stopped, v4)
%7|1504599213.831|OP|rdkafka#consumer-1| [thrd:main]: sess5lichun [1] received op PAUSE (v4) in fetch-state stopped (opv3)
%7|1504599213.831|FETCH|rdkafka#consumer-1| [thrd:10.137.75.134:9092/bootstrap]: 10.137.75.134:9092/3: Topic sess5lichun [1] in state stopped at offset 0 (0/100000 msgs, 0/1000000 kb queued, opv 2) is not fetchable: not in active fetch state
%7|1504599213.831|FETCHADD|rdkafka#consumer-1| [thrd:10.137.75.134:9092/bootstrap]: 10.137.75.134:9092/3: Removed sess5lichun [1] from fetch list (0 entries, opv 2)
%7|1504599213.831|RESUME|rdkafka#consumer-1| [thrd:main]: Not resuming stopped sess5lichun [1]: at offset 0 (state stopped, v4)
%7|1504599213.831|CGRPOP|rdkafka#consumer-1| [thrd:main]: Group "sess5lichun" received op PARTITION_LEAVE in state up (join state wait-unassign, v6) for sess5lichun [0]
%7|1504599213.831|PARTDEL|rdkafka#consumer-1| [thrd:main]: Group "sess5lichun": delete sess5lichun [0]
%7|1504599213.831|CGRPOP|rdkafka#consumer-1| [thrd:main]: Group "sess5lichun" received op REPLY:FETCH_STOP in state up (join state wait-unassign, v6) for sess5lichun [0]
%7|1504599213.831|UNASSIGN|rdkafka#consumer-1| [thrd:main]: Unassign not done yet (1 wait_unassign, 1 assigned, 0 wait commit): FETCH_STOP done
%7|1504599213.831|CGRPOP|rdkafka#consumer-1| [thrd:main]: Group "sess5lichun" received op PARTITION_LEAVE in state up (join state wait-unassign, v6) for sess5lichun [1]
%7|1504599213.831|PARTDEL|rdkafka#consumer-1| [thrd:main]: Group "sess5lichun": delete sess5lichun [1]
%7|1504599213.831|CGRPOP|rdkafka#consumer-1| [thrd:main]: Group "sess5lichun" received op REPLY:FETCH_STOP in state up (join state wait-unassign, v6) for sess5lichun [1]
%7|1504599213.831|UNASSIGN|rdkafka#consumer-1| [thrd:main]: Group "sess5lichun": unassign done in state up (join state wait-unassign): with new assignment: FETCH_STOP done
%7|1504599213.831|CGRPJOINSTATE|rdkafka#consumer-1| [thrd:main]: Group "sess5lichun" changed join state wait-unassign -> assigned (v6, state up)
%7|1504599213.831|BARRIER|rdkafka#consumer-1| [thrd:main]: Group "sess5lichun": rd_kafka_cgrp_partitions_fetch_start0:1599: new version barrier v7
%7|1504599213.831|FETCHSTART|rdkafka#consumer-1| [thrd:main]: Group "sess5lichun": starting fetchers for 2 assigned partition(s) in join-state assigned (usable_offsets=no, v7, line 2094)
%7|1504599213.831|FETCHSTART|rdkafka#consumer-1| [thrd:main]: List with 2 partition(s):
%7|1504599213.831|FETCHSTART|rdkafka#consumer-1| [thrd:main]:  sess5lichun [0] offset BEGINNING
%7|1504599213.831|FETCHSTART|rdkafka#consumer-1| [thrd:main]:  sess5lichun [1] offset BEGINNING
%7|1504599213.831|OFFSET|rdkafka#consumer-1| [thrd:main]: Fetch 2 offsets with v7
%7|1504599213.831|OFFSET|rdkafka#consumer-1| [thrd:main]: 10.137.75.134:9092/3: OffsetFetchRequest: skipping sess5lichun [0] with valid offset BEGINNING
%7|1504599213.831|OFFSET|rdkafka#consumer-1| [thrd:main]: 10.137.75.134:9092/3: OffsetFetchRequest: skipping sess5lichun [1] with valid offset BEGINNING
%7|1504599213.831|OFFSET|rdkafka#consumer-1| [thrd:main]: 10.137.75.134:9092/3: OffsetFetchRequest(v1) for 0/2 partition(s)
%7|1504599213.831|OFFSETFETCH|rdkafka#consumer-1| [thrd:main]: List with 2 partition(s):
%7|1504599213.831|OFFSETFETCH|rdkafka#consumer-1| [thrd:main]:  sess5lichun [0] offset BEGINNING
%7|1504599213.831|OFFSETFETCH|rdkafka#consumer-1| [thrd:main]:  sess5lichun [1] offset BEGINNING
%7|1504599213.831|BARRIER|rdkafka#consumer-1| [thrd:main]: Group "sess5lichun": rd_kafka_cgrp_partitions_fetch_start0:1599: new version barrier v8
%7|1504599213.831|FETCHSTART|rdkafka#consumer-1| [thrd:main]: Group "sess5lichun": starting fetchers for 2 assigned partition(s) in join-state assigned (usable_offsets=yes, v8, line 1528)
%7|1504599213.831|FETCHSTART|rdkafka#consumer-1| [thrd:main]: List with 2 partition(s):
%7|1504599213.831|FETCHSTART|rdkafka#consumer-1| [thrd:main]:  sess5lichun [0] offset BEGINNING
%7|1504599213.831|FETCHSTART|rdkafka#consumer-1| [thrd:main]:  sess5lichun [1] offset BEGINNING
%7|1504599213.831|CGRPJOINSTATE|rdkafka#consumer-1| [thrd:main]: Group "sess5lichun" changed join state assigned -> started (v8, state up)
%7|1504599213.831|BARRIER|rdkafka#consumer-1| [thrd:main]: sess5lichun [0]: rd_kafka_toppar_op_fetch_start:2054: new version barrier v5
%7|1504599213.831|CONSUMER|rdkafka#consumer-1| [thrd:main]: Start consuming sess5lichun [0] at offset BEGINNING (v5)
%7|1504599213.831|BARRIER|rdkafka#consumer-1| [thrd:main]: sess5lichun [1]: rd_kafka_toppar_op_fetch_start:2054: new version barrier v5
%7|1504599213.831|CONSUMER|rdkafka#consumer-1| [thrd:main]: Start consuming sess5lichun [1] at offset BEGINNING (v5)
%7|1504599213.831|OP|rdkafka#consumer-1| [thrd:main]: sess5lichun [0] received op FETCH_START (v5) in fetch-state stopped (opv4)
%7|1504599213.831|FETCH|rdkafka#consumer-1| [thrd:main]: Start fetch for sess5lichun [0] in state stopped at offset BEGINNING (v5)
%7|1504599213.831|PARTSTATE|rdkafka#consumer-1| [thrd:main]: Partition sess5lichun [0] changed fetch state stopped -> offset-query
%7|1504599213.831|OFFSET|rdkafka#consumer-1| [thrd:main]: sess5lichun [0]: offset reset (at offset BEGINNING) to BEGINNING: update: Success
%7|1504599213.831|OFFREQ|rdkafka#consumer-1| [thrd:main]: 10.137.75.133:9092/2: Partition sess5lichun [0]: querying for logical offset BEGINNING (opv 5)
%7|1504599213.831|OFFSET|rdkafka#consumer-1| [thrd:main]: 10.137.75.133:9092/2: OffsetRequest (v0, opv 0) for 1 topic(s) and 1 partition(s)
%7|1504599213.831|PARTSTATE|rdkafka#consumer-1| [thrd:main]: Partition sess5lichun [0] changed fetch state offset-query -> offset-wait
%7|1504599213.831|OP|rdkafka#consumer-1| [thrd:main]: sess5lichun [1] received op FETCH_START (v5) in fetch-state stopped (opv4)
%7|1504599213.831|FETCH|rdkafka#consumer-1| [thrd:main]: Start fetch for sess5lichun [1] in state stopped at offset BEGINNING (v5)
%7|1504599213.831|PARTSTATE|rdkafka#consumer-1| [thrd:main]: Partition sess5lichun [1] changed fetch state stopped -> offset-query
%7|1504599213.832|OFFSET|rdkafka#consumer-1| [thrd:main]: sess5lichun [1]: offset reset (at offset BEGINNING) to BEGINNING: update: Success
%7|1504599213.832|OFFREQ|rdkafka#consumer-1| [thrd:main]: 10.137.75.134:9092/3: Partition sess5lichun [1]: querying for logical offset BEGINNING (opv 5)
%7|1504599213.832|OFFSET|rdkafka#consumer-1| [thrd:main]: 10.137.75.134:9092/3: OffsetRequest (v0, opv 0) for 1 topic(s) and 1 partition(s)
%7|1504599213.832|PARTSTATE|rdkafka#consumer-1| [thrd:main]: Partition sess5lichun [1] changed fetch state offset-query -> offset-wait
%7|1504599213.832|CGRPOP|rdkafka#consumer-1| [thrd:main]: Group "sess5lichun" received op PARTITION_JOIN in state up (join state started, v8) for sess5lichun [0]
%7|1504599213.832|PARTADD|rdkafka#consumer-1| [thrd:main]: Group "sess5lichun": add sess5lichun [0]
%7|1504599213.832|CGRPOP|rdkafka#consumer-1| [thrd:main]: Group "sess5lichun" received op PARTITION_JOIN in state up (join state started, v8) for sess5lichun [1]
%7|1504599213.832|PARTADD|rdkafka#consumer-1| [thrd:main]: Group "sess5lichun": add sess5lichun [1]
%7|1504599213.833|OFFSET|rdkafka#consumer-1| [thrd:main]: 10.137.75.133:9092/2: Offset reply for topic sess5lichun [0] (v5 vs v5)
%7|1504599213.833|OFFSET|rdkafka#consumer-1| [thrd:main]: Offset BEGINNING request for sess5lichun [0] returned offset 0 (0)
%7|1504599213.833|PARTSTATE|rdkafka#consumer-1| [thrd:main]: Partition sess5lichun [0] changed fetch state offset-wait -> active
%7|1504599213.833|FETCHDEC|rdkafka#consumer-1| [thrd:10.137.75.133:9092/bootstrap]: Topic sess5lichun [0]: fetch decide: updating to version 5 (was 2) at offset 0 (was 2)
%7|1504599213.833|FETCH|rdkafka#consumer-1| [thrd:10.137.75.133:9092/bootstrap]: 10.137.75.133:9092/2: Fetch backoff for 497ms
%7|1504599213.833|FETCH|rdkafka#consumer-1| [thrd:10.137.75.133:9092/bootstrap]: 10.137.75.133:9092/2: Fetch backoff for 496ms
%7|1504599213.843|OFFSET|rdkafka#consumer-1| [thrd:main]: 10.137.75.134:9092/3: Offset reply for topic sess5lichun [1] (v5 vs v5)
%7|1504599213.843|OFFSET|rdkafka#consumer-1| [thrd:main]: Offset BEGINNING request for sess5lichun [1] returned offset 0 (0)
%7|1504599213.843|PARTSTATE|rdkafka#consumer-1| [thrd:main]: Partition sess5lichun [1] changed fetch state offset-wait -> active
%7|1504599213.843|FETCHDEC|rdkafka#consumer-1| [thrd:10.137.75.134:9092/bootstrap]: Topic sess5lichun [1]: fetch decide: updating to version 5 (was 2) at offset 0 (was 4)
%7|1504599213.843|FETCH|rdkafka#consumer-1| [thrd:10.137.75.134:9092/bootstrap]: 10.137.75.134:9092/3: Topic sess5lichun [1] in state active at offset 0 (0/100000 msgs, 0/1000000 kb queued, opv 5) is fetchable: 
%7|1504599213.843|FETCHADD|rdkafka#consumer-1| [thrd:10.137.75.134:9092/bootstrap]: 10.137.75.134:9092/3: Added sess5lichun [1] to fetch list (1 entries, opv 5)
%7|1504599213.843|FETCH|rdkafka#consumer-1| [thrd:10.137.75.134:9092/bootstrap]: 10.137.75.134:9092/3: Fetch topic sess5lichun [1] at offset 0 (v5)
%7|1504599213.843|FETCH|rdkafka#consumer-1| [thrd:10.137.75.134:9092/bootstrap]: 10.137.75.134:9092/3: Fetch 1/1/1 toppar(s)
%7|1504599213.844|CONSUME|rdkafka#consumer-1| [thrd:10.137.75.134:9092/bootstrap]: 10.137.75.134:9092/3: Enqueue 4 message(s) on sess5lichun [1] fetch queue (qlen 4, v5, last_offset 3)
%7|1504599213.844|FETCH|rdkafka#consumer-1| [thrd:10.137.75.134:9092/bootstrap]: 10.137.75.134:9092/3: Fetch topic sess5lichun [1] at offset 4 (v5)
%7|1504599213.844|CGRPOP|rdkafka#consumer-1| [thrd:main]: Group "sess5lichun" received op OFFSET_COMMIT (v0) in state up (join state started, v8 vs 0)
%7|1504599213.844|FETCH|rdkafka#consumer-1| [thrd:10.137.75.134:9092/bootstrap]: 10.137.75.134:9092/3: Fetch 1/1/1 toppar(s)
%7|1504599213.844|OFFSET|rdkafka#consumer-1| [thrd:main]: Topic sess5lichun [0]: stored offset 2, committed offset 2
%7|1504599213.844|OFFSET|rdkafka#consumer-1| [thrd:main]: Topic sess5lichun [0]: setting offset INVALID for commit
%7|1504599213.844|OFFSET|rdkafka#consumer-1| [thrd:main]: Topic sess5lichun [1]: stored offset 1, committed offset 4
%7|1504599213.844|OFFSET|rdkafka#consumer-1| [thrd:main]: Topic sess5lichun [1]: setting offset INVALID for commit
%7|1504599213.844|COMMIT|rdkafka#consumer-1| [thrd:main]: OffsetCommit internal error: Local: No offset stored
%7|1504599213.844|COMMIT|rdkafka#consumer-1| [thrd:main]: OffsetCommit for 2 partition(s): manual: returned: Local: No offset stored
sync commit returned err:Local: No offset stored

**Comment by edenhill** [comment] 2017-09-05 08:37
commit() without any offsets specified will commit the stored offsets, the stored offsets are those that are stored locally in memory for the next commit.
Offset stores take place automatically (if `enable.auto.offset.store` is left at its default true value) as consumed messages are passed to the application.
If there are no messages consumed then no offsets will be stored.
You can manually store offsets for future commits as well by calling offset_store() or offsets_store(),

**Comment by edenhill** [comment] 2017-09-05 08:40
Also, the automatic offset commit will not commit an older offset than the one already committed, which I think is what we are seeing here.

**Comment by hougedengwo** [comment] 2017-09-05 11:39
I still got "No offset stored". Reproduce see below:
I set enable.auto.offset.store=false.
If get valid message when call _consumer->consume(500), then store the message->offset() in local memory.
Manually construct partitions for calling offsets_store() before commitSync().
code segment like this:
  while (run) {
      if (need reset to beginning) {
          std::vector<RdKafka::TopicPartition*> partitions;
          partitions.push_back(RdKafka::TopicPartition::create(_topic
              , _partitionId, RdKafka::Topic::OFFSET_BEGINNING));
          _consumer->assign(partitions);
      }
  
      RdKafka::Message *msg = _consumer->consume(500);
      switch (msg->err()) {
      case RdKafka::ERR__PARTITION_EOF:
          return RdKafka::ERR__PARTITION_EOF;
      case RdKafka::ERR_NO_ERROR:
          stored msg->offset() in local memory
          break;
      ...
      }
      if (consumed messages >= commit batch) {
          construct std::vector<RdKafka::TopicPartition*> partitions with stored offset
          _consumer->offsets_store(partitions);
          RdKafka::ErrorCode err = _consumer->commitSync();
          if (err != RdKafka::ERR_NO_ERROR) {
              std::cerr << "sync commit returned err:"
                  << RdKafka::err2str(err) << std::endl;
          }
      }
  }

**Comment by hougedengwo** [comment] 2017-09-05 12:12
I also tried _consumer->commitSync(std::vector<TopicPartition*> &offsets) with the correct offset, it can resolve the problem.
But it has an another problem: the last message can be consumed and committed correctly, the next calling of consume() function return EOF event, then the test application quit. when I next run the test application, this time I consume message from the last committed offset, It still can get the last message other than EOF event. The last message always can be got. It seemed the last offset not stored by kafka after returned EOF.

**Comment by edenhill** [comment] 2017-09-05 14:34
Do note that the stored (and later committed) offset should be that off the next message, i.e.: msg->offset + 1

**Comment by hougedengwo** [comment] 2017-09-06 01:21
Thank you very much for your help. I have gotten what I want by commitSync(std::vector<TopicPartition*> &offsets).
Thank you again. :)

**Closed** 2017-09-06 08:56 UTC
Labels: consumer, question

**Comment by leileileileilei1** [comment] 2021-08-17 14:32
hi edenhill:  

we have a question for you.

The C++ client version is 1.0.0, and the Kafka version on the server is kafka_2.11-2.2.1. When the data volume exceeds 3 million, the client reports the error rd_kafka_commit Local: No offset stored.

Have similar problems been resolved in the latest librdkafka.a client version?

If the client version is upgraded to 1.7.0, are there any requirements on the server version?

thanks
