### ISSUE TITLE
message.timeout.ms cannot be set to 0 (= infinite)

### ISSUE THREAD

**Issue by sDessens** [edenhill/librdkafka#2283] opened 2019-04-17 12:09 UTC
The documentation for `message.timeout.ms` states that the value of 0 indicates an infinite timeout. However, it is not possible to actually configure a value of 0 because `message.timeout.ms` must be strictly greater than `buffering.max.ms`, which has a minimum value of 0. This check was added in this commit: https://github.com/edenhill/librdkafka/commit/179de512088af2edbfc56860fbe4bc10a76b7d72

The following error message occurs when attempting to set `message.timeout.ms` to zero:

```(Client creation error: `message.timeout.ms` must be greater than `linger.ms`)```

**Comment by edenhill** [comment] 2019-04-18 06:45
Right, and there are also issues with setting message.timeout.ms=0 which causes buggy timeout behaviour, so we'll need to fix that first.
As a workaround I suggest setting message.timeout.ms to its maximum value.

**Comment by edenhill** [comment] 2019-05-27 14:10
Duplicate of #2015

**Closed** 2019-05-27 14:10 UTC
Labels: duplicate

**Comment by artelk** [comment] 2019-08-05 14:04
It seems the issue is not yet fixed in 1.1.0.
That still throws an error `message.timeout.ms must be greater than linger.ms` when message.timeout.ms is 0.
