### ISSUE TITLE
How to improve the efficiency of manual submit offset ?

### ISSUE THREAD

**Issue by DavidLiuXh** [edenhill/librdkafka#945] opened 2016-12-08 14:55 UTC
Description
===========
How to improve the efficiency of manual submit offset ?

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment] 2016-12-08 14:56
Can you try to be specific?

**Comment by DavidLiuXh** [comment] 2016-12-08 15:32
1. Call to rd_kafka_consumer_poll in thread A, push this returns rd_kafka_message to queue Q1;
2. pop msg from queue Q1 and manual submit offset in thead B;
3. tested 3 million msg, it is found that rd_kafka_consumer_poll returns a lot of duplicate data;

**Comment by edenhill** [comment] 2016-12-08 19:39
I guess you mean commit, not submit :)

3. What do you mean by duplicate?  The same message (same topic,partition,offset) received multiple times?
If so that would be an indication that the offset commits are not working, or dont make it in time.

Some questions:
 * Are you using subscribe()?
 * Have you registered a rebalance callback? If so, are you doing anything special there? (you must call assign() from the rebalance callback)
 * Have you registered an offset_commit_cb() to see results of each offset commit? You should

**Comment by DavidLiuXh** [comment] 2016-12-09 03:28
1. I called to subscribe() and rd_kafka_assing();
2. I registered an offset_commit_cb()  callback and result is ok;
3. But rd_kafka_consumer_poll returns a lot of same message(same topic,partition,offset)

**Comment by edenhill** [comment] 2016-12-09 07:47
Qs:
 * Do you change your subscription? (Call subscribe() multiple times?
 * Do you ever call assign() outside of the rebalance callback?

**Comment by DavidLiuXh** [comment] 2016-12-09 07:58
1. only one call subscribe
2. only call to rd_kafka_assing in rebalance callback funciton.
3. This topic has 10 partitions, but I only started a consumer.

**Comment by edenhill** [comment] 2016-12-09 07:59
And you are not using seek() or anything like that?

Can you reproduce this with `debug=topic,fetch,cgrp,msg` enabled and give me the logs?

**Comment by DavidLiuXh** [comment] 2016-12-09 08:05
[rdkafk.log.tar.gz](https://github.com/edenhill/librdkafka/files/641532/rdkafk.log.tar.gz)

**Comment by edenhill** [comment] 2016-12-09 15:22
You seem to be committing for each message which is generally not recommended if you are consuming at a high-rate.

Looking at the logs this large number of offset commits queue up waiting for transmission to the broker and they eventually fail because the group has rebalanced. E.g.:
> ` | RD_KAFKA_LOG | level: 7 | fac: OFFSET | msg: OffsetCommit failed for test_qbus1 [6] at offset 198063: Broker: Specified group generation id is not valid`

I suggest you either use auto commit and set the commit.interval to your like, or keep the manual commits but only commit every say 10000 messages or 100ms, whichever comes first.

**Comment by DavidLiuXh** [comment] 2016-12-09 15:35
Thanks for @edenhill.
Why do rebalance many times?

**Comment by edenhill** [comment] 2016-12-09 15:54
Most likely because the HeartbeatRequests (which are used to indicate that a consumer is still alive in the group) are queued up behind thousands of commit requests

**Comment by DavidLiuXh** [comment] 2016-12-12 08:27
Thanks for @edenhill.
Do I receive duplicate messages when manual commit and failed to commit because rebalance?

**Comment by edenhill** [comment] 2016-12-12 08:28
Yes, if the commit fails the consumer will start at a previous succesfully committed offset when it rebalances, in which case you'll probably see the same messages again.

**Comment by DavidLiuXh** [comment] 2016-12-12 11:07
Whether  can add a configuration to only auto commit offset  for rd_kafka_msg returned   rd_kafka_poll_consumer_poll?

**Comment by edenhill** [comment] 2016-12-12 11:19
That's how it works by default, librdkafka will store the offset (internally in memory) of the last message returned by consumer_poll() (or equivalent function) and then periodically commit that stored offset.

**Comment by DavidLiuXh** [comment] 2016-12-14 02:54
Thanks for @edenhill.

**Closed** 2016-12-14 02:54 UTC
