### ISSUE TITLE
Kerberos for Windows - wrong property for broker principal

### ISSUE THREAD

**Issue by ozac** [edenhill/librdkafka#1438] opened 2017-10-03 21:43 UTC
Description
===========
I think the Kerberos implementation for Windows is using a wrong property.

When constructing the full principal name of the broker at https://github.com/edenhill/librdkafka/blob/master/src/rdkafka_sasl_win32.c#L490
it uses the client's principal (sasl.kerberos.principal, default "kafkaclient"), while it should use the service name (sasl.kerberos.service.name, default "kafka").

On the Wiki page - https://github.com/edenhill/librdkafka/wiki/Using-SASL-with-librdkafka-on-Windows
the example command "solves" it by overriding the default client's principal with "kafka", which is the correct value of the service name:
> rdkafka_example.exe -P -t SOME_TOPIC -b HOST_FQDN:9093 -X security.protocol=SASL_PLAINTEXT -X sasl.kerberos.service.name= kafka/HOST_FQDN@REALM **-X sasl.kerberos.principal=kafka** -d security,protocol,broker

Also, this property is not needed in the command: 
> -X sasl.kerberos.service.name= kafka/HOST_FQDN@REALM

Thanks

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): 0.11, master
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [x] Operating system: Windows
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment] 2017-10-09 09:01
@zyzil Do you have any comments on this?

**Comment by ozac** [comment] 2017-11-09 06:36
Any update?

Thanks

**Comment by zyzil** [comment] 2017-11-09 13:15
Sorry for the delay, it looks like @ozac was correct and @edenhill is working on it related to #1502

**Comment by edenhill** [comment] 2017-11-09 16:51
Sorry @ozac, I didn't see your issue when filing #1502, it is a duplicate of your issue and is fixed on master. Please give it a spin.

**Closed** 2017-11-09 16:51 UTC
Labels: bug, duplicate, windows

**Comment by ozac** [comment] 2017-11-15 12:14
Now it works fine. Tested using rdkafka_example.exe from master.
Thanks!

**Comment by edenhill** [comment] 2017-11-15 12:18
Thanks!
