### ISSUE TITLE
Mapping from RdKafka::ErrorCode::ERR_UNKNOWN_TOPIC_OR_PART to an RdKafka::TopicPartition

### ISSUE THREAD

**Issue by tai-allman** [edenhill/librdkafka#1755] opened 2018-04-05 20:53 UTC
Description
===========
We are trying to use the C++ KafkaConsumer as follows:
Construct a `std::vector<TopicPartition*>` that contains an arbitrary collection of topics and partitions (ie, could all be one topic, could be a bunch of topics with one partition each) with offsets set
use `KafkaConsumer::assign` to set a consumer's assignment
Consume using `auto msg = consumer_->consume(0)`
stop when we reach EOP or encounter an error on all partitions we are consuming from

The problem is that (afaik) `msg->err()` will never be set to `ErrorCode::ERR_UNKNOWN_TOPIC_OR_PART`, if an error of that type is seen it will be passed to the event_cb. That would be fine, but as far as I can tell there is no way to figure out which topic/partition caused the error in the event_cb. Since we want to stop on EOP we need to know which partitions are good and which have caused an error.

Checklist
=========
Please provide the following information:
 - [x] librdkafka version (release number or git tag): `v0.11.3`
 - [x] Apache Kafka version: `1.0.1`
 - [x] librdkafka client configuration: a bunch, but I don't think it's important
 - [x] Operating system: `Ubuntu, RHEL`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by edenhill** [comment] 2018-04-11 09:47
Right, this is indeed an issue.

We'll look into it soon.
Duplicate of: https://github.com/edenhill/librdkafka/issues/1540

**Closed by edenhill** 2018-04-11 09:47 UTC
