### ISSUE TITLE
Offset storage bugs

### ISSUE THREAD

**Issue by DEvil0000** [edenhill/librdkafka#227] opened 2015-03-31 08:38 UTC
It looks like sometimes I get a message less and sometimes one more than expected.
Was working with latest master before 0.8.6. Using C++ interface.

Testcase#1:
* delete offset files
* setup/start producer
* produce 3 messages
* setup/start consumer#1 (topic: test, group:1)
* setup/start consumer#2 (topic:test, group:2)
* offset should point to the end of the topic (position_A)
* consume on 1 & 2 should return without message
* stop consumer#2
* produce 3 messages
* consumer#1 should consume 3 messages (new offset: position_A+3)
* consumer#2 start (should read offset position_A)
* consumer#2 should consume 3 messages (new offset: position_A+3)

What is happening at the moment:
* consumer#2 should consume 3 messages (new offset: position_A+3) << consumes only 2 messages

UPDATE:
here i was recreating the topic when stop/start a consumer

**Comment by DEvil0000** [comment] 2015-04-01 15:32
The following fixes the bug for me:
```
diff --git a/src/rdkafka_offset.c b/src/rdkafka_offset.c
index 8222590..8a3bc45 100644
--- a/src/rdkafka_offset.c
+++ b/src/rdkafka_offset.c
@@ -518,7 +518,7 @@ static void rd_kafka_offset_file_init (rd_kafka_toppar_t *rktp) {
        if (offset != -1) {
                /* Start fetching from offset */
                rktp->rktp_commited_offset = offset;
-               rktp->rktp_next_offset     = offset+1;
+               rktp->rktp_next_offset     = offset;
                rktp->rktp_fetch_state     = RD_KAFKA_TOPPAR_FETCH_ACTIVE;
 
        } else {

```

**Comment by edenhill** [comment] 2015-04-02 06:36
Thanks for your detailed analysis.
Do the regression tests (`make tests`) pass with that change?

**Comment by DEvil0000** [comment] 2015-04-02 12:25
with & without it tests 12 & 14 fail.
For 12 it looks like it fails because of partition 1 is used but my default kafka config creates new topics with only one partition.. -> missing note or call to increase partition count..
```
############## 0012-produce_consume.test ################
### Running test 0012-produce_consume.test in bare mode ###
Using topic "rdkafkatest_0012"
Topic rdkafkatest_0012, testid 4049932114785446833
Created    kafka instance rdkafka#producer-0
Start produce to partition 0
Produced 5000 messages to partition 0, waiting for deliveries
Start produce to partition 1
Produced 5000 messages to partition 1, waiting for deliveries
### Test failed at 0012-produce_consume.c:174:produce_messages(): ###
Still waiting for 5000 messages to be produced
### Test random seed was -180648675 ###
###
### Test 0012-produce_consume.test in bare mode FAILED! ###
###
```
After fixing partition count on topic it was like this
```
############## 0012-produce_consume.test ################
### Running test 0012-produce_consume.test in bare mode ###
Using topic "rdkafkatest_0012"
Topic rdkafkatest_0012, testid 3734662696059593920
Created    kafka instance rdkafka#producer-0
Start produce to partition 0
Produced 5000 messages to partition 0, waiting for deliveries
Start produce to partition 1
Produced 5000 messages to partition 1, waiting for deliveries
Destroying kafka instance rdkafka#producer-0
Created    kafka instance rdkafka#consumer-1
Consuming 5000 messages from partition 0
Destroying kafka instance rdkafka#consumer-1
Created    kafka instance rdkafka#consumer-2
Consuming 5000 messages from partition 1
Destroying kafka instance rdkafka#consumer-2
Created    kafka instance rdkafka#consumer-3
Consuming 10000 messages from one queue serving 2 partitions
Start consuming partition 0 at offset -5000
Start consuming partition 1 at offset -5000
### Test failed at 0012-produce_consume.c:444:consume_messages_with_queues(): ###
Consume message 5000/10000 from queue has error (partition 1): Broker: No more messages
### Test random seed was 322055742 ###
###
### Test 0012-produce_consume.test in bare mode FAILED! ###
###
```
For 14 I have no clue why it fails (maybe offset broker method?)
BTW BUG: this test is called 14 but it uses topic 13!
```
############## 0014-reconsume-191.test ################
### Running test 0014-reconsume-191.test in bare mode ###
Using topic "rdkafkatest_0013"
Topic rdkafkatest_0013, testid 9078722994771939079
Created    kafka instance rdkafka#producer-0
### Test failed at 0014-reconsume-191.c:51:dr_cb(): ###
Message delivery failed: Broker: Invalid message

### Test random seed was -108662397 ###
###
### Test 0014-reconsume-191.test in bare mode FAILED! ###
###
```
using kafka 0.8.2.0

I will take a second look when i have some time.

Additional Hint:
Maybe the #230 thing leads to a different message count in the tests - depending on implementation

**Comment by DEvil0000** [comment] 2015-04-02 13:24
It looks like there is a second bug involved with offsets. Like it is not getting written properly in every case. (i am not sure yet what is the difference to the first case where it is getting written)
I am able to fix it with a call to offset_store(offset+1)
```
            consume()
            //force offset write
            mpaTopic->offset_store(inPartition, pMessage->offset()+1);
```
So this one & the patch above resolves all my offset problems.
I will try to find the cause in the lib to get rid of this manual call to offset_store()

**Comment by DEvil0000** [comment] 2015-04-02 15:57
In some rare cases it is still failing -> maybe multi threading issue (data race/missing mutex) with offset read/write?

**Comment by DEvil0000** [comment] 2015-04-23 14:54
may be related: #258 #259
and at least because i was starting to write something about the tests here ;)

**Comment by DEvil0000** [comment] 2015-06-24 08:46
I am back on this issue.
it looks like some bugs are fixed with latest 'master' branch but I still have issues with the offset.
I removed my dirty fixes in the wrapper and the lib and use it plain and normal again in the new 'version'.
BTW: all your tests worked well with and without my patch above. this is only possible if they don't test for this in a correct way.

I did the same tests with the new master code - here is the important part of the log & some explanation:
```
f23ffb40  TRC  06-24 08:20:23.715  Producer:115            Message acknowledge: message (ReturnCode: Success, Offset: 27, Len: 7, Partition: 1)
f23ffb40  TRC  06-24 08:20:23.717  Producer:115            Message acknowledge: test message (ReturnCode: Success, Offset: 30, Len: 12, Partition: 0)
f23ffb40  TRC  06-24 08:20:23.717  Producer:115            Message acknowledge: another message (ReturnCode: Success, Offset: 31, Len: 15, Partition: 0)

//CONSUMER 1&2 START
//CONSUMER 2 STOP

f599d040  DEB  06-24 08:20:26.780  KafkaConnection:463     LOG-7-OFFSET: test [1]: wrote offset 28 to file /wsp_var/kafka/test-1-group_2.offset

f23ffb40  TRC  06-24 08:20:27.724  Producer:115            Message acknowledge: test message (ReturnCode: Success, Offset: 28, Len: 12, Partition: 1)
f23ffb40  TRC  06-24 08:20:27.724  Producer:115            Message acknowledge: another message (ReturnCode: Success, Offset: 29, Len: 15, Partition: 1)
f23ffb40  TRC  06-24 08:20:27.726  Producer:115            Message acknowledge: message (ReturnCode: Success, Offset: 32, Len: 7, Partition: 0)

eeffbb40  TRC  06-24 08:20:27.946  Consumer:506            Got new message from topic test (Offset: 32, Len: 7)
eeffbb40  TRC  06-24 08:20:27.946  Consumer:506            Got new message from topic test (Offset: 28, Len: 12)

f0fffb40  DEB  06-24 08:20:27.947  KafkaConnection:463     LOG-7-OFFSET: test [0]: wrote offset 32 to file /wsp_var/kafka/test-0-group_1.offset
f0fffb40  DEB  06-24 08:20:27.953  KafkaConnection:463     LOG-7-OFFSET: test [1]: wrote offset 28 to file /wsp_var/kafka/test-1-group_1.offset

eeffbb40  TRC  06-24 08:20:27.976  Consumer:506            Got new message from topic test (Offset: 29, Len: 15)

f0fffb40  DEB  06-24 08:20:28.057  KafkaConnection:463     LOG-7-OFFSET: test [1]: wrote offset 29 to file /wsp_var/kafka/test-1-group_1.offset

//CONSUMER 2 START (should catch up and get same messages)

ec7f6b40  TRC  06-24 08:20:29.805  Consumer:506            Got new message from topic test (Offset: 29, Len: 15)

edff9b40  DEB  06-24 08:20:29.811  KafkaConnection:463     LOG-7-OFFSET: test [1]: wrote offset 29 to file /wsp_var/kafka/test-1-group_2.offset
f599d040  DEB  06-24 08:20:30.811  KafkaConnection:463     LOG-7-OFFSET: test [0]: wrote offset 33 to file /wsp_var/kafka/test-0-group_2.offset

//SHUTDOWN CONSUMERS


PRODUCED MESSAGES BEFORE CONSUMER INIT:
1Messages for partition 1
2Message for partition 0

PRODUCED MESSAGES AFTER CONSUMER INIT:
2Messages for partition 1
1Message for partition 0

EXPECTED RESULTS:
1. consumers should ignore the first produced messaged because offset is not initialized [OK]
2. consumer 1 should consume all 3 messages produced after it was started [OK]
3. consumer 2 should consume all 3 messages after it was started again (offsets should be known from the first start/stop) [FAILED] (only got one message from partition 1 - looks like a offset +/- 1 bug)
4. at the end the offset files for partition 0 (different groups) should have the same value. same for partition 1. [FAILED]

RESULT OFFSETS:
partition 0:
group1: 32
group2: 33

partition 1:
group1&2: 29
```

**Comment by edenhill** [comment] 2015-06-24 10:29
````
eeffbb40  TRC  06-24 08:20:27.946  Consumer:506            Got new message from topic test (Offset: 32, Len: 7)
eeffbb40  TRC  06-24 08:20:27.946  Consumer:506            Got new message from topic test (Offset: 28, Len: 12)
````

are you receiving these messages out of order, 32 before 28?

**Comment by DEvil0000** [comment] 2015-06-24 12:03
yes but this is fine - they are on different partitions and order is only guaranteed within a partition.
the problem is the offset

**Comment by DEvil0000** [comment] 2015-06-25 13:04
you closed the two other tickets - but I think we have at least 3 different bugs involved with offsets.
* file based offset is not stored correct between runs (save on stop/on receive)
* broker based offset is not fetched (or stored) correct (offset is always 0 at my test system)
* file based offset stored value is +/-1 from what it should be | first fetched message is skipped in some cases

**Comment by edenhill** [comment] 2015-06-25 15:57
Thanks for summarizing that.

**Comment by DEvil0000** [comment] 2015-06-29 13:39
more infos on broker based offset bug:
fetch tells me:
`LOG-7-OFFSET: ubuntu:9092/0: Offset (type 9) reply error for consumer lag topic test [1]: Broker: Unknown topic or partition`
what seams to be the error code for "no offset stored for topic/group/partition".

after digging deeper it looks like the offset is never sent to kafka server.
it looks like the offset is never getting set in librdkafka (to something else then `-1`) when using broker based offsets.

**Comment by DEvil0000** [comment] 2015-09-02 15:45
tested again with latest dev (05c68970bb5a4195306a89048dbb345535e21f33).
at least one offset bug is still open for me (broker & file based storage). it is the one described at the beginning of this ticket.
simplified test setup description: two groups on one topic with two partitions.
still the same wrong behaviour for this.

**Comment by edenhill** [comment] 2015-09-02 16:38
Are your two consumers using the same rd_kafka_t handle?

**Comment by edenhill** [comment] 2015-09-03 09:12
@DEvil0000 See above question.

librdkafka currently does not have consumer group support, which means you need to use two different consumer handles to consume the same topic+partition from different offsets.

**Comment by DEvil0000** [comment] 2015-09-04 09:12
sry for the late answer.
I am using different consumer handles `RdKafka::Handle* pKafkaHandle = RdKafka::Consumer::create( mpaGlobalConfig, sError );` with different configs `mpaGlobalConfig = RdKafka::Conf::create( RdKafka::Conf::CONF_GLOBAL );`.
if there is no hidden re-use code going on they should be different instances.

**Comment by edenhill** [comment] 2015-09-04 09:15
They are completely separate instances, sharing nothing.
As long as you dont use the same offset storage file for both of them I dont think the issue is related to running multiple consumers simultaneously.

Are you only seeing this with dual consumers and not one?
Is it reproducible with something like kafkacat?

**Comment by edenhill** [comment] 2015-09-04 09:15
I'm on IRC freenode as Snaps if that helps

**Comment by DEvil0000** [comment] 2015-09-14 12:08
as discussed in irc:
multiple consumers on the same topic with multiple partitions still fail to write/read the correct offset.
the bug described in this post is still there (tested on 05c68970bb5a4195306a89048dbb345535e21f33)

**Comment by edenhill** [comment] 2015-12-14 21:34
Fixed on master

**Closed by edenhill** 2015-12-14 21:34 UTC
Labels: bug, consumer
